language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "2.7"
services:
  - redis-server
  - postgresql
env:
  - REDIS_URL=redis://localhost:6379
  - DATABASE_URL=postgres://postgres:@localhost/travis_ci_test
  - SQLALCHEMY_DATABASE_URI=postgres://postgres:@localhost/travis_ci_test
  - SQLALCHEMY_MIGRATE_REPO=db_repository
  - SECRET_KEY=A0Zr98j3yXR~XHHjdmN]LWXRT
  - SECURITY_PASSWORD_SALT=2bb10883-6724-42cb-a538-f41543393880
  - APP_MAIL_USERNAME=ivo@xxx.se
  - APP_MAIL_PASSWORD=xxx
  - DEBUG=True
  - FLASK_DEBUG=1
  - DROPBOX=cxxx
  - MINIFY_PAGE=False
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create --name test-environment python=2.7
  - source activate test-environment
  - conda install nomkl
  - conda install pip --yes
  - conda install --file conda-requirements.txt --yes
  - pip install -r requirements.txt  --exists-action=w --allow-all-external
  - conda install matplotlib=1.5.3
  - pip install honcho
  
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cd tests
script:
  - honcho -e .env-test start