/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : PostgreSQL
 Source Server Version : 90405
 Source Host           : localhost
 Source Database       : aidhedge
 Source Schema         : public

 Target Server Type    : PostgreSQL
 Target Server Version : 90405
 File Encoding         : utf-8

 Date: 01/24/2017 14:01:36 PM
*/
--  cat sql-dumps/public.sql | docker exec -i faad1886fd38 psql -U postgres
-- ----------------------------
--  Table structure for all_currencies
-- ----------------------------
CREATE TABLE "public"."all_currencies" (
	"id" int4 NOT NULL,
	"country" varchar(255) COLLATE "default",
	"currency" varchar(255) COLLATE "default",
	"code" text COLLATE "default"
)
WITH (OIDS=FALSE);
ALTER TABLE "public"."all_currencies" OWNER TO "postgres";

-- ----------------------------
--  Records of all_currencies
-- ----------------------------
BEGIN;
INSERT INTO "public"."all_currencies" VALUES ('1', 'Afghanistan', 'Afghan afghani', 'AFN');
INSERT INTO "public"."all_currencies" VALUES ('2', 'Akrotiri and Dhekelia (UK)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('3', 'Aland Islands (Finland)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('4', 'Albania', 'Albanian lek', 'ALL');
INSERT INTO "public"."all_currencies" VALUES ('5', 'Algeria', 'Algerian dinar', 'DZD');
INSERT INTO "public"."all_currencies" VALUES ('6', 'American Samoa (USA)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('7', 'Andorra', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('8', 'Angola', 'Angolan kwanza', 'AOA');
INSERT INTO "public"."all_currencies" VALUES ('9', 'Anguilla (UK)', 'East Caribbean dollar', 'XCD');
INSERT INTO "public"."all_currencies" VALUES ('10', 'Antigua and Barbuda', 'East Caribbean dollar', 'XCD');
INSERT INTO "public"."all_currencies" VALUES ('11', 'Argentina', 'Argentine peso', 'ARS');
INSERT INTO "public"."all_currencies" VALUES ('12', 'Armenia', 'Armenian dram', 'AMD');
INSERT INTO "public"."all_currencies" VALUES ('13', 'Aruba (Netherlands)', 'Aruban florin', 'AWG');
INSERT INTO "public"."all_currencies" VALUES ('14', 'Ascension Island (UK)', 'Saint Helena pound', 'SHP');
INSERT INTO "public"."all_currencies" VALUES ('15', 'Australia', 'Australian dollar', 'AUD');
INSERT INTO "public"."all_currencies" VALUES ('16', 'Austria', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('17', 'Azerbaijan', 'Azerbaijani manat', 'AZN');
INSERT INTO "public"."all_currencies" VALUES ('18', 'Bahamas', 'Bahamian dollar', 'BSD');
INSERT INTO "public"."all_currencies" VALUES ('19', 'Bahrain', 'Bahraini dinar', 'BHD');
INSERT INTO "public"."all_currencies" VALUES ('20', 'Bangladesh', 'Bangladeshi taka', 'BDT');
INSERT INTO "public"."all_currencies" VALUES ('21', 'Barbados', 'Barbadian dollar', 'BBD');
INSERT INTO "public"."all_currencies" VALUES ('22', 'Belarus', 'Belarusian ruble', 'BYN');
INSERT INTO "public"."all_currencies" VALUES ('23', 'Belgium', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('24', 'Belize', 'Belize dollar', 'BZD');
INSERT INTO "public"."all_currencies" VALUES ('25', 'Benin', 'West African CFA franc', 'XOF');
INSERT INTO "public"."all_currencies" VALUES ('26', 'Bermuda (UK)', 'Bermudian dollar', 'BMD');
INSERT INTO "public"."all_currencies" VALUES ('27', 'Bhutan', 'Bhutanese ngultrum', 'BTN');
INSERT INTO "public"."all_currencies" VALUES ('28', 'Bolivia', 'Bolivian boliviano', 'BOB');
INSERT INTO "public"."all_currencies" VALUES ('29', 'Bonaire (Netherlands)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('30', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina convertible mark', 'BAM');
INSERT INTO "public"."all_currencies" VALUES ('31', 'Botswana', 'Botswana pula', 'BWP');
INSERT INTO "public"."all_currencies" VALUES ('32', 'Brazil', 'Brazilian real', 'BRL');
INSERT INTO "public"."all_currencies" VALUES ('33', 'British Indian Ocean Territory (UK)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('34', 'British Virgin Islands (UK)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('35', 'Brunei', 'Brunei dollar', 'BND');
INSERT INTO "public"."all_currencies" VALUES ('36', 'Bulgaria', 'Bulgarian lev', 'BGN');
INSERT INTO "public"."all_currencies" VALUES ('37', 'Burkina Faso', 'West African CFA franc', 'XOF');
INSERT INTO "public"."all_currencies" VALUES ('38', 'Burundi', 'Burundi franc', 'BIF');
INSERT INTO "public"."all_currencies" VALUES ('39', 'Cabo Verde', 'Cape Verdean escudo', 'CVE');
INSERT INTO "public"."all_currencies" VALUES ('40', 'Cambodia', 'Cambodian riel', 'KHR');
INSERT INTO "public"."all_currencies" VALUES ('41', 'Cameroon', 'Central African CFA franc', 'XAF');
INSERT INTO "public"."all_currencies" VALUES ('42', 'Canada', 'Canadian dollar', 'CAD');
INSERT INTO "public"."all_currencies" VALUES ('43', 'Caribbean Netherlands (Netherlands)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('44', 'Cayman Islands (UK)', 'Cayman Islands dollar', 'KYD');
INSERT INTO "public"."all_currencies" VALUES ('45', 'Central African Republic', 'Central African CFA franc', 'XAF');
INSERT INTO "public"."all_currencies" VALUES ('46', 'Chad', 'Central African CFA franc', 'XAF');
INSERT INTO "public"."all_currencies" VALUES ('47', 'Chile', 'Chilean peso', 'CLP');
INSERT INTO "public"."all_currencies" VALUES ('48', 'China', 'Chinese Yuan Renminbi', 'CNY');
INSERT INTO "public"."all_currencies" VALUES ('49', 'Christmas Island (Australia)', 'Australian dollar', 'AUD');
INSERT INTO "public"."all_currencies" VALUES ('50', 'Cocos (Keeling) Islands (Australia)', 'Australian dollar', 'AUD');
INSERT INTO "public"."all_currencies" VALUES ('51', 'Colombia', 'Colombian peso', 'COP');
INSERT INTO "public"."all_currencies" VALUES ('52', 'Comoros', 'Comorian franc', 'KMF');
INSERT INTO "public"."all_currencies" VALUES ('53', 'Congo, Democratic Republic of the', 'Congolese franc', 'CDF');
INSERT INTO "public"."all_currencies" VALUES ('54', 'Congo, Republic of the', 'Central African CFA franc', 'XAF');
INSERT INTO "public"."all_currencies" VALUES ('55', 'Cook Islands (New Zealand)', 'Cook Islands dollar', 'none');
INSERT INTO "public"."all_currencies" VALUES ('56', 'Costa Rica', 'Costa Rican colon', 'CRC');
INSERT INTO "public"."all_currencies" VALUES ('57', 'Cote d''Ivoire', 'West African CFA franc', 'XOF');
INSERT INTO "public"."all_currencies" VALUES ('58', 'Croatia', 'Croatian kuna', 'HRK');
INSERT INTO "public"."all_currencies" VALUES ('59', 'Cuba', 'Cuban peso', 'CUP');
INSERT INTO "public"."all_currencies" VALUES ('60', 'Curacao (Netherlands)', 'Netherlands Antillean guilder', 'ANG');
INSERT INTO "public"."all_currencies" VALUES ('61', 'Cyprus', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('62', 'Czech Republic', 'Czech koruna', 'CZK');
INSERT INTO "public"."all_currencies" VALUES ('63', 'Denmark', 'Danish krone', 'DKK');
INSERT INTO "public"."all_currencies" VALUES ('64', 'Djibouti', 'Djiboutian franc', 'DJF');
INSERT INTO "public"."all_currencies" VALUES ('65', 'Dominica', 'East Caribbean dollar', 'XCD');
INSERT INTO "public"."all_currencies" VALUES ('66', 'Dominican Republic', 'Dominican peso', 'DOP');
INSERT INTO "public"."all_currencies" VALUES ('67', 'Ecuador', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('68', 'Egypt', 'Egyptian pound', 'EGP');
INSERT INTO "public"."all_currencies" VALUES ('69', 'El Salvador', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('70', 'Equatorial Guinea', 'Central African CFA franc', 'XAF');
INSERT INTO "public"."all_currencies" VALUES ('71', 'Eritrea', 'Eritrean nakfa', 'ERN');
INSERT INTO "public"."all_currencies" VALUES ('72', 'Estonia', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('73', 'Ethiopia', 'Ethiopian birr', 'ETB');
INSERT INTO "public"."all_currencies" VALUES ('74', 'Falkland Islands (UK)', 'Falkland Islands pound', 'FKP');
INSERT INTO "public"."all_currencies" VALUES ('75', 'Faroe Islands (Denmark)', 'Faroese krona', 'none');
INSERT INTO "public"."all_currencies" VALUES ('76', 'Fiji', 'Fijian dollar', 'FJD');
INSERT INTO "public"."all_currencies" VALUES ('77', 'Finland', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('78', 'France', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('79', 'French Guiana (France)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('80', 'French Polynesia (France)', 'CFP franc', 'XPF');
INSERT INTO "public"."all_currencies" VALUES ('81', 'Gabon', 'Central African CFA franc', 'XAF');
INSERT INTO "public"."all_currencies" VALUES ('82', 'Gambia', 'Gambian dalasi', 'GMD');
INSERT INTO "public"."all_currencies" VALUES ('83', 'Georgia', 'Georgian lari', 'GEL');
INSERT INTO "public"."all_currencies" VALUES ('84', 'Germany', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('85', 'Ghana', 'Ghanaian cedi', 'GHS');
INSERT INTO "public"."all_currencies" VALUES ('86', 'Gibraltar (UK)', 'Gibraltar pound', 'GIP');
INSERT INTO "public"."all_currencies" VALUES ('87', 'Greece', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('88', 'Greenland (Denmark)', 'Danish krone', 'DKK');
INSERT INTO "public"."all_currencies" VALUES ('89', 'Grenada', 'East Caribbean dollar', 'XCD');
INSERT INTO "public"."all_currencies" VALUES ('90', 'Guadeloupe (France)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('91', 'Guam (USA)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('92', 'Guatemala', 'Guatemalan quetzal', 'GTQ');
INSERT INTO "public"."all_currencies" VALUES ('93', 'Guernsey (UK)', 'Guernsey Pound', 'GGP');
INSERT INTO "public"."all_currencies" VALUES ('94', 'Guinea', 'Guinean franc', 'GNF');
INSERT INTO "public"."all_currencies" VALUES ('95', 'Guinea-Bissau', 'West African CFA franc', 'XOF');
INSERT INTO "public"."all_currencies" VALUES ('96', 'Guyana', 'Guyanese dollar', 'GYD');
INSERT INTO "public"."all_currencies" VALUES ('97', 'Haiti', 'Haitian gourde', 'HTG');
INSERT INTO "public"."all_currencies" VALUES ('98', 'Honduras', 'Honduran lempira', 'HNL');
INSERT INTO "public"."all_currencies" VALUES ('99', 'Hong Kong (China)', 'Hong Kong dollar', 'HKD');
INSERT INTO "public"."all_currencies" VALUES ('100', 'Hungary', 'Hungarian forint', 'HUF');
INSERT INTO "public"."all_currencies" VALUES ('101', 'Iceland', 'Icelandic krona', 'ISK');
INSERT INTO "public"."all_currencies" VALUES ('102', 'India', 'Indian rupee', 'INR');
INSERT INTO "public"."all_currencies" VALUES ('103', 'Indonesia', 'Indonesian rupiah', 'IDR');
INSERT INTO "public"."all_currencies" VALUES ('104', 'International Monetary Fund (IMF)', 'SDR (Special Drawing Right)', 'XDR');
INSERT INTO "public"."all_currencies" VALUES ('105', 'Iran', 'Iranian rial', 'IRR');
INSERT INTO "public"."all_currencies" VALUES ('106', 'Iraq', 'Iraqi dinar', 'IQD');
INSERT INTO "public"."all_currencies" VALUES ('107', 'Ireland', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('108', 'Isle of Man (UK)', 'Manx pound', 'IMP');
INSERT INTO "public"."all_currencies" VALUES ('109', 'Israel', 'Israeli new shekel', 'ILS');
INSERT INTO "public"."all_currencies" VALUES ('110', 'Italy', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('111', 'Jamaica', 'Jamaican dollar', 'JMD');
INSERT INTO "public"."all_currencies" VALUES ('112', 'Japan', 'Japanese yen', 'JPY');
INSERT INTO "public"."all_currencies" VALUES ('113', 'Jersey (UK)', 'Jersey pound', 'JEP');
INSERT INTO "public"."all_currencies" VALUES ('114', 'Jordan', 'Jordanian dinar', 'JOD');
INSERT INTO "public"."all_currencies" VALUES ('115', 'Kazakhstan', 'Kazakhstani tenge', 'KZT');
INSERT INTO "public"."all_currencies" VALUES ('116', 'Kenya', 'Kenyan shilling', 'KES');
INSERT INTO "public"."all_currencies" VALUES ('117', 'Kiribati', 'Australian dollar', 'AUD');
INSERT INTO "public"."all_currencies" VALUES ('118', 'Kosovo', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('119', 'Kuwait', 'Kuwaiti dinar', 'KWD');
INSERT INTO "public"."all_currencies" VALUES ('120', 'Kyrgyzstan', 'Kyrgyzstani som', 'KGS');
INSERT INTO "public"."all_currencies" VALUES ('121', 'Laos', 'Lao kip', 'LAK');
INSERT INTO "public"."all_currencies" VALUES ('122', 'Latvia', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('123', 'Lebanon', 'Lebanese pound', 'LBP');
INSERT INTO "public"."all_currencies" VALUES ('124', 'Lesotho', 'Lesotho loti', 'LSL');
INSERT INTO "public"."all_currencies" VALUES ('125', 'Liberia', 'Liberian dollar', 'LRD');
INSERT INTO "public"."all_currencies" VALUES ('126', 'Libya', 'Libyan dinar', 'LYD');
INSERT INTO "public"."all_currencies" VALUES ('127', 'Liechtenstein', 'Swiss franc', 'CHF');
INSERT INTO "public"."all_currencies" VALUES ('128', 'Lithuania', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('129', 'Luxembourg', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('130', 'Macau (China)', 'Macanese pataca', 'MOP');
INSERT INTO "public"."all_currencies" VALUES ('131', 'Macedonia', 'Macedonian denar', 'MKD');
INSERT INTO "public"."all_currencies" VALUES ('132', 'Madagascar', 'Malagasy ariary', 'MGA');
INSERT INTO "public"."all_currencies" VALUES ('133', 'Malawi', 'Malawian kwacha', 'MWK');
INSERT INTO "public"."all_currencies" VALUES ('134', 'Malaysia', 'Malaysian ringgit', 'MYR');
INSERT INTO "public"."all_currencies" VALUES ('135', 'Maldives', 'Maldivian rufiyaa', 'MVR');
INSERT INTO "public"."all_currencies" VALUES ('136', 'Mali', 'West African CFA franc', 'XOF');
INSERT INTO "public"."all_currencies" VALUES ('137', 'Malta', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('138', 'Marshall Islands', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('139', 'Martinique (France)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('140', 'Mauritania', 'Mauritanian ouguiya', 'MRO');
INSERT INTO "public"."all_currencies" VALUES ('141', 'Mauritius', 'Mauritian rupee', 'MUR');
INSERT INTO "public"."all_currencies" VALUES ('142', 'Mayotte (France)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('143', 'Mexico', 'Mexican peso', 'MXN');
INSERT INTO "public"."all_currencies" VALUES ('144', 'Micronesia', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('145', 'Moldova', 'Moldovan leu', 'MDL');
INSERT INTO "public"."all_currencies" VALUES ('146', 'Monaco', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('147', 'Mongolia', 'Mongolian tugrik', 'MNT');
INSERT INTO "public"."all_currencies" VALUES ('148', 'Montenegro', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('149', 'Montserrat (UK)', 'East Caribbean dollar', 'XCD');
INSERT INTO "public"."all_currencies" VALUES ('150', 'Morocco', 'Moroccan dirham', 'MAD');
INSERT INTO "public"."all_currencies" VALUES ('151', 'Mozambique', 'Mozambican metical', 'MZN');
INSERT INTO "public"."all_currencies" VALUES ('152', 'Myanmar (Burma)', 'Myanmar kyat', 'MMK');
INSERT INTO "public"."all_currencies" VALUES ('153', 'Namibia', 'Namibian dollar', 'NAD');
INSERT INTO "public"."all_currencies" VALUES ('154', 'Nauru', 'Australian dollar', 'AUD');
INSERT INTO "public"."all_currencies" VALUES ('155', 'Nepal', 'Nepalese rupee', 'NPR');
INSERT INTO "public"."all_currencies" VALUES ('156', 'Netherlands', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('157', 'New Caledonia (France)', 'CFP franc', 'XPF');
INSERT INTO "public"."all_currencies" VALUES ('158', 'New Zealand', 'New Zealand dollar', 'NZD');
INSERT INTO "public"."all_currencies" VALUES ('159', 'Nicaragua', 'Nicaraguan cordoba', 'NIO');
INSERT INTO "public"."all_currencies" VALUES ('160', 'Niger', 'West African CFA franc', 'XOF');
INSERT INTO "public"."all_currencies" VALUES ('161', 'Nigeria', 'Nigerian naira', 'NGN');
INSERT INTO "public"."all_currencies" VALUES ('162', 'Niue (New Zealand)', 'New Zealand dollar', 'NZD');
INSERT INTO "public"."all_currencies" VALUES ('163', 'Norfolk Island (Australia)', 'Australian dollar', 'AUD');
INSERT INTO "public"."all_currencies" VALUES ('164', 'Northern Mariana Islands (USA)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('165', 'North Korea', 'North Korean won', 'KPW');
INSERT INTO "public"."all_currencies" VALUES ('166', 'Norway', 'Norwegian krone', 'NOK');
INSERT INTO "public"."all_currencies" VALUES ('167', 'Oman', 'Omani rial', 'OMR');
INSERT INTO "public"."all_currencies" VALUES ('168', 'Pakistan', 'Pakistani rupee', 'PKR');
INSERT INTO "public"."all_currencies" VALUES ('169', 'Palau', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('170', 'Palestine', 'Israeli new shekel', 'ILS');
INSERT INTO "public"."all_currencies" VALUES ('171', 'Panama', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('172', 'Papua New Guinea', 'Papua New Guinean kina', 'PGK');
INSERT INTO "public"."all_currencies" VALUES ('173', 'Paraguay', 'Paraguayan guarani', 'PYG');
INSERT INTO "public"."all_currencies" VALUES ('174', 'Peru', 'Peruvian sol', 'PEN');
INSERT INTO "public"."all_currencies" VALUES ('175', 'Philippines', 'Philippine peso', 'PHP');
INSERT INTO "public"."all_currencies" VALUES ('176', 'Pitcairn Islands (UK)', 'New Zealand dollar', 'NZD');
INSERT INTO "public"."all_currencies" VALUES ('177', 'Poland', 'Polish zloty', 'PLN');
INSERT INTO "public"."all_currencies" VALUES ('178', 'Portugal', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('179', 'Puerto Rico (USA)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('180', 'Qatar', 'Qatari riyal', 'QAR');
INSERT INTO "public"."all_currencies" VALUES ('181', 'Reunion (France)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('182', 'Romania', 'Romanian leu', 'RON');
INSERT INTO "public"."all_currencies" VALUES ('183', 'Russia', 'Russian ruble', 'RUB');
INSERT INTO "public"."all_currencies" VALUES ('184', 'Rwanda', 'Rwandan franc', 'RWF');
INSERT INTO "public"."all_currencies" VALUES ('185', 'Saba (Netherlands)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('186', 'Saint Barthelemy (France)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('187', 'Saint Helena (UK)', 'Saint Helena pound', 'SHP');
INSERT INTO "public"."all_currencies" VALUES ('188', 'Saint Kitts and Nevis', 'East Caribbean dollar', 'XCD');
INSERT INTO "public"."all_currencies" VALUES ('189', 'Saint Lucia', 'East Caribbean dollar', 'XCD');
INSERT INTO "public"."all_currencies" VALUES ('190', 'Saint Martin (France)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('191', 'Saint Pierre and Miquelon (France)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('192', 'Saint Vincent and the Grenadines', 'East Caribbean dollar', 'XCD');
INSERT INTO "public"."all_currencies" VALUES ('193', 'Samoa', 'Samoan tala', 'WST');
INSERT INTO "public"."all_currencies" VALUES ('194', 'San Marino', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('195', 'Sao Tome and Principe', 'Sao Tome and Principe dobra', 'STD');
INSERT INTO "public"."all_currencies" VALUES ('196', 'Saudi Arabia', 'Saudi Arabian riyal', 'SAR');
INSERT INTO "public"."all_currencies" VALUES ('197', 'Senegal', 'West African CFA franc', 'XOF');
INSERT INTO "public"."all_currencies" VALUES ('198', 'Serbia', 'Serbian dinar', 'RSD');
INSERT INTO "public"."all_currencies" VALUES ('199', 'Seychelles', 'Seychellois rupee', 'SCR');
INSERT INTO "public"."all_currencies" VALUES ('200', 'Sierra Leone', 'Sierra Leonean leone', 'SLL');
INSERT INTO "public"."all_currencies" VALUES ('201', 'Singapore', 'Singapore dollar', 'SGD');
INSERT INTO "public"."all_currencies" VALUES ('202', 'Sint Eustatius (Netherlands)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('203', 'Sint Maarten (Netherlands)', 'Netherlands Antillean guilder', 'ANG');
INSERT INTO "public"."all_currencies" VALUES ('204', 'Slovakia', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('205', 'Slovenia', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('206', 'Solomon Islands', 'Solomon Islands dollar', 'SBD');
INSERT INTO "public"."all_currencies" VALUES ('207', 'Somalia', 'Somali shilling', 'SOS');
INSERT INTO "public"."all_currencies" VALUES ('208', 'South Africa', 'South African rand', 'ZAR');
INSERT INTO "public"."all_currencies" VALUES ('209', 'South Georgia Island (UK)', 'Pound sterling', 'GBP');
INSERT INTO "public"."all_currencies" VALUES ('210', 'South Korea', 'South Korean won', 'KRW');
INSERT INTO "public"."all_currencies" VALUES ('211', 'South Sudan', 'South Sudanese pound', 'SSP');
INSERT INTO "public"."all_currencies" VALUES ('212', 'Spain', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('213', 'Sri Lanka', 'Sri Lankan rupee', 'LKR');
INSERT INTO "public"."all_currencies" VALUES ('214', 'Sudan', 'Sudanese pound', 'SDG');
INSERT INTO "public"."all_currencies" VALUES ('215', 'Suriname', 'Surinamese dollar', 'SRD');
INSERT INTO "public"."all_currencies" VALUES ('216', 'Svalbard and Jan Mayen (Norway)', 'Norwegian krone', 'NOK');
INSERT INTO "public"."all_currencies" VALUES ('217', 'Swaziland', 'Swazi lilangeni', 'SZL');
INSERT INTO "public"."all_currencies" VALUES ('218', 'Sweden', 'Swedish krona', 'SEK');
INSERT INTO "public"."all_currencies" VALUES ('219', 'Switzerland', 'Swiss franc', 'CHF');
INSERT INTO "public"."all_currencies" VALUES ('220', 'Syria', 'Syrian pound', 'SYP');
INSERT INTO "public"."all_currencies" VALUES ('221', 'Taiwan', 'New Taiwan dollar', 'TWD');
INSERT INTO "public"."all_currencies" VALUES ('222', 'Tajikistan', 'Tajikistani somoni', 'TJS');
INSERT INTO "public"."all_currencies" VALUES ('223', 'Tanzania', 'Tanzanian shilling', 'TZS');
INSERT INTO "public"."all_currencies" VALUES ('224', 'Thailand', 'Thai baht', 'THB');
INSERT INTO "public"."all_currencies" VALUES ('225', 'Timor-Leste', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('226', 'Togo', 'West African CFA franc', 'XOF');
INSERT INTO "public"."all_currencies" VALUES ('227', 'Tokelau (New Zealand)', 'New Zealand dollar', 'NZD');
INSERT INTO "public"."all_currencies" VALUES ('228', 'Tonga', 'Tongan pa’anga', 'TOP');
INSERT INTO "public"."all_currencies" VALUES ('229', 'Trinidad and Tobago', 'Trinidad and Tobago dollar', 'TTD');
INSERT INTO "public"."all_currencies" VALUES ('230', 'Tristan da Cunha (UK)', 'Pound sterling', 'GBP');
INSERT INTO "public"."all_currencies" VALUES ('231', 'Tunisia', 'Tunisian dinar', 'TND');
INSERT INTO "public"."all_currencies" VALUES ('232', 'Turkey', 'Turkish lira', 'TRY');
INSERT INTO "public"."all_currencies" VALUES ('233', 'Turkmenistan', 'Turkmen manat', 'TMT');
INSERT INTO "public"."all_currencies" VALUES ('234', 'Turks and Caicos Islands (UK)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('235', 'Tuvalu', 'Australian dollar', 'AUD');
INSERT INTO "public"."all_currencies" VALUES ('236', 'Uganda', 'Ugandan shilling', 'UGX');
INSERT INTO "public"."all_currencies" VALUES ('237', 'Ukraine', 'Ukrainian hryvnia', 'UAH');
INSERT INTO "public"."all_currencies" VALUES ('238', 'United Arab Emirates', 'UAE dirham', 'AED');
INSERT INTO "public"."all_currencies" VALUES ('239', 'United Kingdom', 'Pound sterling', 'GBP');
INSERT INTO "public"."all_currencies" VALUES ('240', 'United States of America', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('241', 'Uruguay', 'Uruguayan peso', 'UYU');
INSERT INTO "public"."all_currencies" VALUES ('242', 'US Virgin Islands (USA)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('243', 'Uzbekistan', 'Uzbekistani som', 'UZS');
INSERT INTO "public"."all_currencies" VALUES ('244', 'Vanuatu', 'Vanuatu vatu', 'VUV');
INSERT INTO "public"."all_currencies" VALUES ('245', 'Vatican City (Holy See)', 'European euro', 'EUR');
INSERT INTO "public"."all_currencies" VALUES ('246', 'Venezuela', 'Venezuelan bolivar', 'VEF');
INSERT INTO "public"."all_currencies" VALUES ('247', 'Vietnam', 'Vietnamese dong', 'VND');
INSERT INTO "public"."all_currencies" VALUES ('248', 'Wake Island (USA)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('249', 'Wallis and Futuna (France)', 'CFP franc', 'XPF');
INSERT INTO "public"."all_currencies" VALUES ('250', 'Yemen', 'Yemeni rial', 'YER');
INSERT INTO "public"."all_currencies" VALUES ('251', 'Zambia', 'Zambian kwacha', 'ZMW');
INSERT INTO "public"."all_currencies" VALUES ('252', 'Zimbabwe', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('253', 'UK (Dfid and other)', 'Pound sterling', 'GBP');
INSERT INTO "public"."all_currencies" VALUES ('254', 'Sweden (Sida and other)', 'Swedish krona', 'SEK');
INSERT INTO "public"."all_currencies" VALUES ('255', 'Norway (Norad and other)', 'Norwegian krone', 'NOK');
INSERT INTO "public"."all_currencies" VALUES ('256', 'US (USAID and other)', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('258', 'United Nations', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('259', 'World Bank', 'United States dollar', 'USD');
INSERT INTO "public"."all_currencies" VALUES ('257', 'European Union or Commission', 'European euro', 'EUR');
COMMIT;

-- ----------------------------
--  Table structure for country_codes
-- ----------------------------

CREATE TABLE "public"."country_codes" (
	"id" int4 NOT NULL,
	"country" varchar(255) COLLATE "default",
	"code" text COLLATE "default"
)
WITH (OIDS=FALSE);
ALTER TABLE "public"."country_codes" OWNER TO "postgres";

-- ----------------------------
--  Records of country_codes
-- ----------------------------
BEGIN;
INSERT INTO "public"."country_codes" VALUES ('1', 'Afghanistan', 'AF');
INSERT INTO "public"."country_codes" VALUES ('2', 'Akrotiri Sovereign Base Area', 'AX');
INSERT INTO "public"."country_codes" VALUES ('3', 'Albania', 'AL');
INSERT INTO "public"."country_codes" VALUES ('4', 'Algeria', 'AG');
INSERT INTO "public"."country_codes" VALUES ('5', 'American Samoa', 'AQ');
INSERT INTO "public"."country_codes" VALUES ('6', 'Andorra', 'AN');
INSERT INTO "public"."country_codes" VALUES ('7', 'Angola', 'AO');
INSERT INTO "public"."country_codes" VALUES ('8', 'Anguilla', 'AV');
INSERT INTO "public"."country_codes" VALUES ('9', 'Antarctica', 'AY');
INSERT INTO "public"."country_codes" VALUES ('10', 'Antigua and Barbuda', 'AC');
INSERT INTO "public"."country_codes" VALUES ('11', 'Argentina', 'AR');
INSERT INTO "public"."country_codes" VALUES ('12', 'Armenia', 'AM');
INSERT INTO "public"."country_codes" VALUES ('13', 'Aruba', 'AA');
INSERT INTO "public"."country_codes" VALUES ('14', 'Ashmore and Cartier Islands', 'AT');
INSERT INTO "public"."country_codes" VALUES ('15', 'Australia', 'AS');
INSERT INTO "public"."country_codes" VALUES ('16', 'Austria', 'AU');
INSERT INTO "public"."country_codes" VALUES ('17', 'Azerbaijan', 'AJ');
INSERT INTO "public"."country_codes" VALUES ('18', 'Bahamas', 'BF');
INSERT INTO "public"."country_codes" VALUES ('19', 'Bahrain', 'BA');
INSERT INTO "public"."country_codes" VALUES ('20', 'Baker Island', 'FQ');
INSERT INTO "public"."country_codes" VALUES ('21', 'Bangladesh', 'BG');
INSERT INTO "public"."country_codes" VALUES ('22', 'Barbados', 'BB');
INSERT INTO "public"."country_codes" VALUES ('23', 'Bassas da India', 'BS');
INSERT INTO "public"."country_codes" VALUES ('24', 'Belarus', 'BO');
INSERT INTO "public"."country_codes" VALUES ('25', 'Belgium', 'BE');
INSERT INTO "public"."country_codes" VALUES ('26', 'Belize', 'BH');
INSERT INTO "public"."country_codes" VALUES ('27', 'Benin', 'BN');
INSERT INTO "public"."country_codes" VALUES ('28', 'Bermuda', 'BD');
INSERT INTO "public"."country_codes" VALUES ('29', 'Bhutan', 'BT');
INSERT INTO "public"."country_codes" VALUES ('30', 'Bolivia', 'BL');
INSERT INTO "public"."country_codes" VALUES ('31', 'Bosnia-Herzegovina', 'BK');
INSERT INTO "public"."country_codes" VALUES ('32', 'Botswana', 'BC');
INSERT INTO "public"."country_codes" VALUES ('33', 'Bouvet Island', 'BV');
INSERT INTO "public"."country_codes" VALUES ('34', 'Brazil', 'BR');
INSERT INTO "public"."country_codes" VALUES ('35', 'British Indian Ocean Territory', 'IO');
INSERT INTO "public"."country_codes" VALUES ('36', 'British Virgin Islands', 'VI');
INSERT INTO "public"."country_codes" VALUES ('37', 'Brunei', 'BX');
INSERT INTO "public"."country_codes" VALUES ('38', 'Bulgaria', 'BU');
INSERT INTO "public"."country_codes" VALUES ('39', 'Burkina Faso', 'UV');
INSERT INTO "public"."country_codes" VALUES ('40', 'Burundi', 'BY');
INSERT INTO "public"."country_codes" VALUES ('41', 'Cambodia', 'CB');
INSERT INTO "public"."country_codes" VALUES ('42', 'Cameroon', 'CM');
INSERT INTO "public"."country_codes" VALUES ('43', 'Canada', 'CA');
INSERT INTO "public"."country_codes" VALUES ('44', 'Cape Verde', 'CV');
INSERT INTO "public"."country_codes" VALUES ('45', 'Cayman Islands', 'CJ');
INSERT INTO "public"."country_codes" VALUES ('46', 'Central African Republic', 'CT');
INSERT INTO "public"."country_codes" VALUES ('47', 'Chad', 'CD');
INSERT INTO "public"."country_codes" VALUES ('48', 'Chile', 'CI');
INSERT INTO "public"."country_codes" VALUES ('49', 'China', 'CH');
INSERT INTO "public"."country_codes" VALUES ('50', 'Christmas Island', 'KT');
INSERT INTO "public"."country_codes" VALUES ('51', 'Clipperton Island', 'IP');
INSERT INTO "public"."country_codes" VALUES ('52', 'Cocos Keeling Islands', 'CK');
INSERT INTO "public"."country_codes" VALUES ('53', 'Colombia', 'CO');
INSERT INTO "public"."country_codes" VALUES ('54', 'Comoros', 'CN');
INSERT INTO "public"."country_codes" VALUES ('55', 'Congo', 'CF');
INSERT INTO "public"."country_codes" VALUES ('56', 'Cook Islands', 'CW');
INSERT INTO "public"."country_codes" VALUES ('57', 'Coral Sea Islands', 'CR');
INSERT INTO "public"."country_codes" VALUES ('58', 'Costa Rica', 'CS');
INSERT INTO "public"."country_codes" VALUES ('59', 'Cote dIvoire', 'IV');
INSERT INTO "public"."country_codes" VALUES ('60', 'Croatia', 'HR');
INSERT INTO "public"."country_codes" VALUES ('61', 'Cuba', 'CU');
INSERT INTO "public"."country_codes" VALUES ('62', 'Cyprus', 'CY');
INSERT INTO "public"."country_codes" VALUES ('63', 'Czech Republic', 'EZ');
INSERT INTO "public"."country_codes" VALUES ('64', 'Czechoslovakia', 'LO');
INSERT INTO "public"."country_codes" VALUES ('65', 'Democratic Republic of the Congo', 'CG');
INSERT INTO "public"."country_codes" VALUES ('66', 'Denmark', 'DA');
INSERT INTO "public"."country_codes" VALUES ('67', 'Dhekelia Sovereign Base Area', 'DX');
INSERT INTO "public"."country_codes" VALUES ('68', 'Djibouti', 'DJ');
INSERT INTO "public"."country_codes" VALUES ('69', 'Dominica', 'DO');
INSERT INTO "public"."country_codes" VALUES ('70', 'Dominican Republic', 'DR');
INSERT INTO "public"."country_codes" VALUES ('71', 'East Timor', 'TT');
INSERT INTO "public"."country_codes" VALUES ('72', 'Ecuador', 'EC');
INSERT INTO "public"."country_codes" VALUES ('73', 'Egypt', 'EG');
INSERT INTO "public"."country_codes" VALUES ('74', 'El Salvador', 'ES');
INSERT INTO "public"."country_codes" VALUES ('75', 'Equatorial Guinea', 'GV');
INSERT INTO "public"."country_codes" VALUES ('76', 'Equatorial Guinea', 'EK');
INSERT INTO "public"."country_codes" VALUES ('77', 'Eritrea', 'ER');
INSERT INTO "public"."country_codes" VALUES ('78', 'Estonia', 'EN');
INSERT INTO "public"."country_codes" VALUES ('79', 'Ethiopia', 'ET');
INSERT INTO "public"."country_codes" VALUES ('80', 'Etorofu', 'PJ');
INSERT INTO "public"."country_codes" VALUES ('81', 'Europa Island', 'EU');
INSERT INTO "public"."country_codes" VALUES ('82', 'Falkland Islands Islas Malvinas', 'FK');
INSERT INTO "public"."country_codes" VALUES ('83', 'Faroe Islands', 'FO');
INSERT INTO "public"."country_codes" VALUES ('84', 'Fiji', 'FJ');
INSERT INTO "public"."country_codes" VALUES ('85', 'Finland', 'FI');
INSERT INTO "public"."country_codes" VALUES ('86', 'France', 'FR');
INSERT INTO "public"."country_codes" VALUES ('87', 'French Guiana', 'FG');
INSERT INTO "public"."country_codes" VALUES ('88', 'French Polynesia', 'FP');
INSERT INTO "public"."country_codes" VALUES ('89', 'French Southern and Antarctic Lands', 'FS');
INSERT INTO "public"."country_codes" VALUES ('90', 'Gabon', 'GB');
INSERT INTO "public"."country_codes" VALUES ('91', 'Gambia', 'GA');
INSERT INTO "public"."country_codes" VALUES ('92', 'Gaza Strip', 'GZ');
INSERT INTO "public"."country_codes" VALUES ('93', 'Georgia', 'GG');
INSERT INTO "public"."country_codes" VALUES ('94', 'Germany', 'GM');
INSERT INTO "public"."country_codes" VALUES ('95', 'Ghana', 'GH');
INSERT INTO "public"."country_codes" VALUES ('96', 'Gibraltar', 'GI');
INSERT INTO "public"."country_codes" VALUES ('97', 'Glorioso Islands', 'GO');
INSERT INTO "public"."country_codes" VALUES ('98', 'Greece', 'GR');
INSERT INTO "public"."country_codes" VALUES ('99', 'Greenland', 'GL');
INSERT INTO "public"."country_codes" VALUES ('100', 'Grenada', 'GJ');
INSERT INTO "public"."country_codes" VALUES ('101', 'Guadeloupe', 'GP');
INSERT INTO "public"."country_codes" VALUES ('102', 'Guam', 'GQ');
INSERT INTO "public"."country_codes" VALUES ('103', 'Guatemala', 'GT');
INSERT INTO "public"."country_codes" VALUES ('104', 'Guernsey', 'GK');
INSERT INTO "public"."country_codes" VALUES ('105', 'Guinea-Bissau', 'PU');
INSERT INTO "public"."country_codes" VALUES ('106', 'Guyana', 'GY');
INSERT INTO "public"."country_codes" VALUES ('107', 'Haiti', 'HA');
INSERT INTO "public"."country_codes" VALUES ('108', 'Heard Island and McDonald Islands', 'HM');
INSERT INTO "public"."country_codes" VALUES ('109', 'Honduras', 'HO');
INSERT INTO "public"."country_codes" VALUES ('110', 'Hong Kong', 'HK');
INSERT INTO "public"."country_codes" VALUES ('111', 'Howland Island', 'HQ');
INSERT INTO "public"."country_codes" VALUES ('112', 'Hungary', 'HU');
INSERT INTO "public"."country_codes" VALUES ('113', 'Iceland', 'IC');
INSERT INTO "public"."country_codes" VALUES ('114', 'India', 'IN');
INSERT INTO "public"."country_codes" VALUES ('115', 'Indonesia', 'ID');
INSERT INTO "public"."country_codes" VALUES ('116', 'Iran', 'IR');
INSERT INTO "public"."country_codes" VALUES ('117', 'Iraq', 'IZ');
INSERT INTO "public"."country_codes" VALUES ('118', 'Ireland', 'EI');
INSERT INTO "public"."country_codes" VALUES ('119', 'Isle of Man', 'IM');
INSERT INTO "public"."country_codes" VALUES ('120', 'Israel', 'IS');
INSERT INTO "public"."country_codes" VALUES ('121', 'Italy', 'IT');
INSERT INTO "public"."country_codes" VALUES ('122', 'Jamaica', 'JM');
INSERT INTO "public"."country_codes" VALUES ('123', 'Jan Mayen', 'JN');
INSERT INTO "public"."country_codes" VALUES ('124', 'Japan', 'JA');
INSERT INTO "public"."country_codes" VALUES ('125', 'Jarvis Island', 'DQ');
INSERT INTO "public"."country_codes" VALUES ('126', 'Jersey', 'JE');
INSERT INTO "public"."country_codes" VALUES ('127', 'Johnston Atoll', 'JQ');
INSERT INTO "public"."country_codes" VALUES ('128', 'Jordan', 'JO');
INSERT INTO "public"."country_codes" VALUES ('129', 'Juan de Nova Island', 'JU');
INSERT INTO "public"."country_codes" VALUES ('130', 'Kazakhstan', 'KZ');
INSERT INTO "public"."country_codes" VALUES ('131', 'Kenya', 'KE');
INSERT INTO "public"."country_codes" VALUES ('132', 'Kingman Reef', 'KQ');
INSERT INTO "public"."country_codes" VALUES ('133', 'Kiribati', 'KR');
INSERT INTO "public"."country_codes" VALUES ('134', 'Kosovo', 'KV');
INSERT INTO "public"."country_codes" VALUES ('135', 'Kuwait', 'KU');
INSERT INTO "public"."country_codes" VALUES ('136', 'Kyrgyzstan', 'KG');
INSERT INTO "public"."country_codes" VALUES ('137', 'Laos', 'LA');
INSERT INTO "public"."country_codes" VALUES ('138', 'Latvia', 'LG');
INSERT INTO "public"."country_codes" VALUES ('139', 'Lebanon', 'LE');
INSERT INTO "public"."country_codes" VALUES ('140', 'Lesotho', 'LT');
INSERT INTO "public"."country_codes" VALUES ('141', 'Liberia', 'LI');
INSERT INTO "public"."country_codes" VALUES ('142', 'Libya', 'LY');
INSERT INTO "public"."country_codes" VALUES ('143', 'Liechtenstein', 'LS');
INSERT INTO "public"."country_codes" VALUES ('144', 'Lithuania', 'LH');
INSERT INTO "public"."country_codes" VALUES ('145', 'Luxembourg', 'LU');
INSERT INTO "public"."country_codes" VALUES ('146', 'Macau', 'MC');
INSERT INTO "public"."country_codes" VALUES ('147', 'Macedonia', 'MK');
INSERT INTO "public"."country_codes" VALUES ('148', 'Madagascar', 'MA');
INSERT INTO "public"."country_codes" VALUES ('149', 'Malawi', 'MI');
INSERT INTO "public"."country_codes" VALUES ('150', 'Malaysia', 'MY');
INSERT INTO "public"."country_codes" VALUES ('151', 'Maldives', 'MV');
INSERT INTO "public"."country_codes" VALUES ('152', 'Mali', 'ML');
INSERT INTO "public"."country_codes" VALUES ('153', 'Malta', 'MT');
INSERT INTO "public"."country_codes" VALUES ('154', 'Marshall Islands', 'RM');
INSERT INTO "public"."country_codes" VALUES ('155', 'Martinique', 'MB');
INSERT INTO "public"."country_codes" VALUES ('156', 'Mauritania', 'MR');
INSERT INTO "public"."country_codes" VALUES ('157', 'Mauritius', 'MP');
INSERT INTO "public"."country_codes" VALUES ('158', 'Mayotte', 'MF');
INSERT INTO "public"."country_codes" VALUES ('159', 'Mexico', 'MX');
INSERT INTO "public"."country_codes" VALUES ('160', 'Micronesia', 'FM');
INSERT INTO "public"."country_codes" VALUES ('161', 'Midway Islands', 'MQ');
INSERT INTO "public"."country_codes" VALUES ('162', 'Moldova', 'MD');
INSERT INTO "public"."country_codes" VALUES ('163', 'Monaco', 'MN');
INSERT INTO "public"."country_codes" VALUES ('164', 'Mongolia', 'MG');
INSERT INTO "public"."country_codes" VALUES ('165', 'Montenegro', 'MJ');
INSERT INTO "public"."country_codes" VALUES ('166', 'Montserrat', 'MH');
INSERT INTO "public"."country_codes" VALUES ('167', 'Morocco', 'MO');
INSERT INTO "public"."country_codes" VALUES ('168', 'Mozambique', 'MZ');
INSERT INTO "public"."country_codes" VALUES ('169', 'Myanmar', 'BM');
INSERT INTO "public"."country_codes" VALUES ('170', 'Namibia', 'WA');
INSERT INTO "public"."country_codes" VALUES ('171', 'Nauru', 'NR');
INSERT INTO "public"."country_codes" VALUES ('172', 'Navassa Island', 'BQ');
INSERT INTO "public"."country_codes" VALUES ('173', 'Nepal', 'NP');
INSERT INTO "public"."country_codes" VALUES ('174', 'Netherlands', 'NL');
INSERT INTO "public"."country_codes" VALUES ('175', 'Netherlands Antilles', 'NT');
INSERT INTO "public"."country_codes" VALUES ('176', 'New Caledonia', 'NC');
INSERT INTO "public"."country_codes" VALUES ('177', 'New Zealand', 'NZ');
INSERT INTO "public"."country_codes" VALUES ('178', 'Nicaragua', 'NU');
INSERT INTO "public"."country_codes" VALUES ('179', 'Niger', 'NG');
INSERT INTO "public"."country_codes" VALUES ('180', 'Nigeria', 'NI');
INSERT INTO "public"."country_codes" VALUES ('181', 'Niue', 'NE');
INSERT INTO "public"."country_codes" VALUES ('182', 'No Mans Land', 'NM');
INSERT INTO "public"."country_codes" VALUES ('183', 'Norfolk Island', 'NF');
INSERT INTO "public"."country_codes" VALUES ('184', 'North Korea', 'KN');
INSERT INTO "public"."country_codes" VALUES ('185', 'Northern Mariana Islands', 'CQ');
INSERT INTO "public"."country_codes" VALUES ('186', 'Norway', 'NO');
INSERT INTO "public"."country_codes" VALUES ('187', 'Oceans', 'OS');
INSERT INTO "public"."country_codes" VALUES ('188', 'Oman', 'MU');
INSERT INTO "public"."country_codes" VALUES ('189', 'Pakistan', 'PK');
INSERT INTO "public"."country_codes" VALUES ('190', 'Palau', 'PS');
INSERT INTO "public"."country_codes" VALUES ('191', 'Palmyra Atoll', 'LQ');
INSERT INTO "public"."country_codes" VALUES ('192', 'Panama', 'PM');
INSERT INTO "public"."country_codes" VALUES ('193', 'Papua New Guinea', 'PP');
INSERT INTO "public"."country_codes" VALUES ('194', 'Paracel Islands', 'PF');
INSERT INTO "public"."country_codes" VALUES ('195', 'Paraguay', 'PA');
INSERT INTO "public"."country_codes" VALUES ('196', 'Peru', 'PE');
INSERT INTO "public"."country_codes" VALUES ('197', 'Philippines', 'RP');
INSERT INTO "public"."country_codes" VALUES ('198', 'Pitcairn Islands', 'PC');
INSERT INTO "public"."country_codes" VALUES ('199', 'Poland', 'PL');
INSERT INTO "public"."country_codes" VALUES ('200', 'Portugal', 'PO');
INSERT INTO "public"."country_codes" VALUES ('201', 'Puerto Rico', 'RQ');
INSERT INTO "public"."country_codes" VALUES ('202', 'Qatar', 'QA');
INSERT INTO "public"."country_codes" VALUES ('203', 'Reunion', 'RE');
INSERT INTO "public"."country_codes" VALUES ('204', 'Romania', 'RO');
INSERT INTO "public"."country_codes" VALUES ('205', 'Russia', 'RS');
INSERT INTO "public"."country_codes" VALUES ('206', 'Rwanda', 'RW');
INSERT INTO "public"."country_codes" VALUES ('207', 'Saint Helena', 'SH');
INSERT INTO "public"."country_codes" VALUES ('208', 'Saint Kitts and Nevis', 'SC');
INSERT INTO "public"."country_codes" VALUES ('209', 'Saint Lucia', 'ST');
INSERT INTO "public"."country_codes" VALUES ('210', 'Saint Martin', 'RN');
INSERT INTO "public"."country_codes" VALUES ('211', 'Saint Pierre and Miquelon', 'SB');
INSERT INTO "public"."country_codes" VALUES ('212', 'Saint Vincent and the Grenadines', 'VC');
INSERT INTO "public"."country_codes" VALUES ('213', 'Saint-Barthelemy Island', 'TB');
INSERT INTO "public"."country_codes" VALUES ('214', 'Samoa', 'WS');
INSERT INTO "public"."country_codes" VALUES ('215', 'San Marino', 'SM');
INSERT INTO "public"."country_codes" VALUES ('216', 'Sao Tome and Principe', 'TP');
INSERT INTO "public"."country_codes" VALUES ('217', 'Saudi Arabia', 'SA');
INSERT INTO "public"."country_codes" VALUES ('218', 'Senegal', 'SG');
INSERT INTO "public"."country_codes" VALUES ('219', 'Serbia', 'RI');
INSERT INTO "public"."country_codes" VALUES ('220', 'Seychelles', 'SE');
INSERT INTO "public"."country_codes" VALUES ('221', 'Sierra Leone', 'SL');
INSERT INTO "public"."country_codes" VALUES ('222', 'Singapore', 'SN');
INSERT INTO "public"."country_codes" VALUES ('223', 'Slovenia', 'SI');
INSERT INTO "public"."country_codes" VALUES ('224', 'Solomon Islands', 'BP');
INSERT INTO "public"."country_codes" VALUES ('225', 'Somalia', 'SO');
INSERT INTO "public"."country_codes" VALUES ('226', 'South Africa', 'SF');
INSERT INTO "public"."country_codes" VALUES ('227', 'South Georgia and the South Sandwich Islands', 'SX');
INSERT INTO "public"."country_codes" VALUES ('228', 'South Korea', 'KS');
INSERT INTO "public"."country_codes" VALUES ('229', 'South Sudan', 'OD');
INSERT INTO "public"."country_codes" VALUES ('230', 'Spain', 'SP');
INSERT INTO "public"."country_codes" VALUES ('231', 'Spratly Islands', 'PG');
INSERT INTO "public"."country_codes" VALUES ('232', 'Sri Lanka', 'CE');
INSERT INTO "public"."country_codes" VALUES ('233', 'Sudan', 'SU');
INSERT INTO "public"."country_codes" VALUES ('234', 'Suriname', 'NS');
INSERT INTO "public"."country_codes" VALUES ('235', 'Svalbard', 'SV');
INSERT INTO "public"."country_codes" VALUES ('236', 'Swaziland', 'WZ');
INSERT INTO "public"."country_codes" VALUES ('237', 'Sweden', 'SW');
INSERT INTO "public"."country_codes" VALUES ('238', 'Switzerland', 'SZ');
INSERT INTO "public"."country_codes" VALUES ('239', 'Syria', 'SY');
INSERT INTO "public"."country_codes" VALUES ('240', 'Taiwan', 'TW');
INSERT INTO "public"."country_codes" VALUES ('241', 'Tajikistan', 'TI');
INSERT INTO "public"."country_codes" VALUES ('242', 'Tanzania', 'TZ');
INSERT INTO "public"."country_codes" VALUES ('243', 'Thailand', 'TH');
INSERT INTO "public"."country_codes" VALUES ('244', 'Togo', 'TO');
INSERT INTO "public"."country_codes" VALUES ('245', 'Tokelau', 'TL');
INSERT INTO "public"."country_codes" VALUES ('246', 'Tonga', 'TN');
INSERT INTO "public"."country_codes" VALUES ('247', 'Trinidad and Tobago', 'TD');
INSERT INTO "public"."country_codes" VALUES ('248', 'Tromelin Island', 'TE');
INSERT INTO "public"."country_codes" VALUES ('249', 'Tunisia', 'TS');
INSERT INTO "public"."country_codes" VALUES ('250', 'Turkey', 'TU');
INSERT INTO "public"."country_codes" VALUES ('251', 'Turkmenistan', 'TX');
INSERT INTO "public"."country_codes" VALUES ('252', 'Turks and Caicos Islands', 'TK');
INSERT INTO "public"."country_codes" VALUES ('253', 'Tuvalu', 'TV');
INSERT INTO "public"."country_codes" VALUES ('254', 'Uganda', 'UG');
INSERT INTO "public"."country_codes" VALUES ('255', 'Ukraine', 'UP');
INSERT INTO "public"."country_codes" VALUES ('256', 'Undersea Features', 'UF');
INSERT INTO "public"."country_codes" VALUES ('257', 'Undesignated Sovereignty', 'UU');
INSERT INTO "public"."country_codes" VALUES ('258', 'United Arab Emirates', 'AE');
INSERT INTO "public"."country_codes" VALUES ('259', 'United Kingdom', 'UK');
INSERT INTO "public"."country_codes" VALUES ('260', 'United States', 'US');
INSERT INTO "public"."country_codes" VALUES ('261', 'Uruguay', 'UY');
INSERT INTO "public"."country_codes" VALUES ('262', 'Uzbekistan', 'UZ');
INSERT INTO "public"."country_codes" VALUES ('263', 'Vanuatu', 'NH');
INSERT INTO "public"."country_codes" VALUES ('264', 'Vatican City', 'VT');
INSERT INTO "public"."country_codes" VALUES ('265', 'Venezuela', 'VE');
INSERT INTO "public"."country_codes" VALUES ('266', 'Vietnam', 'VM');
INSERT INTO "public"."country_codes" VALUES ('267', 'Virgin Islands', 'VQ');
INSERT INTO "public"."country_codes" VALUES ('268', 'Wake Island', 'WQ');
INSERT INTO "public"."country_codes" VALUES ('269', 'Wallis and Futuna', 'WF');
INSERT INTO "public"."country_codes" VALUES ('270', 'West Bank', 'WE');
INSERT INTO "public"."country_codes" VALUES ('271', 'Western Sahara', 'WI');
INSERT INTO "public"."country_codes" VALUES ('272', 'Yemen', 'YM');
INSERT INTO "public"."country_codes" VALUES ('273', 'Zambia', 'ZA');
INSERT INTO "public"."country_codes" VALUES ('274', 'Zimbabwe', 'ZI');
COMMIT;

-- ----------------------------
--  Table structure for supported_currencies
-- ----------------------------

CREATE TABLE "public"."supported_currencies" (
	"id" int4 NOT NULL,
	"currency" varchar(255) COLLATE "default",
	"code" text COLLATE "default"
)
WITH (OIDS=FALSE);
ALTER TABLE "public"."supported_currencies" OWNER TO "postgres";

-- ----------------------------
--  Records of supported_currencies
-- ----------------------------
BEGIN;
INSERT INTO "public"."supported_currencies" VALUES ('1', 'United Arab Emirates Dirham', 'AED');
INSERT INTO "public"."supported_currencies" VALUES ('2', 'Afghan Afghani', 'AFN');
INSERT INTO "public"."supported_currencies" VALUES ('3', 'Albanian Lek', 'ALL');
INSERT INTO "public"."supported_currencies" VALUES ('4', 'Armenian Dram', 'AMD');
INSERT INTO "public"."supported_currencies" VALUES ('5', 'Netherlands Antillean Guilder', 'ANG');
INSERT INTO "public"."supported_currencies" VALUES ('6', 'Angolan Kwanza', 'AOA');
INSERT INTO "public"."supported_currencies" VALUES ('7', 'Argentine Peso', 'ARS');
INSERT INTO "public"."supported_currencies" VALUES ('8', 'Australian Dollar', 'AUD');
INSERT INTO "public"."supported_currencies" VALUES ('9', 'Aruban Florin', 'AWG');
INSERT INTO "public"."supported_currencies" VALUES ('10', 'Azerbaijani Manat', 'AZN');
INSERT INTO "public"."supported_currencies" VALUES ('11', 'Bosnia-Herzegovina Convertible Mark', 'BAM');
INSERT INTO "public"."supported_currencies" VALUES ('12', 'Barbadian Dollar', 'BBD');
INSERT INTO "public"."supported_currencies" VALUES ('13', 'Bangladeshi Taka', 'BDT');
INSERT INTO "public"."supported_currencies" VALUES ('14', 'Bulgarian Lev', 'BGN');
INSERT INTO "public"."supported_currencies" VALUES ('15', 'Bahraini Dinar', 'BHD');
INSERT INTO "public"."supported_currencies" VALUES ('16', 'Burundian Franc', 'BIF');
INSERT INTO "public"."supported_currencies" VALUES ('17', 'Bermudan Dollar', 'BMD');
INSERT INTO "public"."supported_currencies" VALUES ('18', 'Brunei Dollar', 'BND');
INSERT INTO "public"."supported_currencies" VALUES ('19', 'Bolivian Boliviano', 'BOB');
INSERT INTO "public"."supported_currencies" VALUES ('20', 'Brazilian Real', 'BRL');
INSERT INTO "public"."supported_currencies" VALUES ('21', 'Bahamian Dollar', 'BSD');
INSERT INTO "public"."supported_currencies" VALUES ('22', 'Bitcoin', 'BTC');
INSERT INTO "public"."supported_currencies" VALUES ('23', 'Bhutanese Ngultrum', 'BTN');
INSERT INTO "public"."supported_currencies" VALUES ('24', 'Botswanan Pula', 'BWP');
INSERT INTO "public"."supported_currencies" VALUES ('25', 'Belarusian Ruble', 'BYR');
INSERT INTO "public"."supported_currencies" VALUES ('26', 'Belize Dollar', 'BZD');
INSERT INTO "public"."supported_currencies" VALUES ('27', 'Canadian Dollar', 'CAD');
INSERT INTO "public"."supported_currencies" VALUES ('28', 'Congolese Franc', 'CDF');
INSERT INTO "public"."supported_currencies" VALUES ('29', 'Swiss Franc', 'CHF');
INSERT INTO "public"."supported_currencies" VALUES ('30', 'Chilean Unit of Account (UF)', 'CLF');
INSERT INTO "public"."supported_currencies" VALUES ('31', 'Chilean Peso', 'CLP');
INSERT INTO "public"."supported_currencies" VALUES ('32', 'Chinese Yuan', 'CNY');
INSERT INTO "public"."supported_currencies" VALUES ('33', 'Colombian Peso', 'COP');
INSERT INTO "public"."supported_currencies" VALUES ('34', 'Costa Rican Colón', 'CRC');
INSERT INTO "public"."supported_currencies" VALUES ('35', 'Cuban Convertible Peso', 'CUC');
INSERT INTO "public"."supported_currencies" VALUES ('36', 'Cuban Peso', 'CUP');
INSERT INTO "public"."supported_currencies" VALUES ('37', 'Cape Verdean Escudo', 'CVE');
INSERT INTO "public"."supported_currencies" VALUES ('38', 'Czech Republic Koruna', 'CZK');
INSERT INTO "public"."supported_currencies" VALUES ('39', 'Djiboutian Franc', 'DJF');
INSERT INTO "public"."supported_currencies" VALUES ('40', 'Danish Krone', 'DKK');
INSERT INTO "public"."supported_currencies" VALUES ('41', 'Dominican Peso', 'DOP');
INSERT INTO "public"."supported_currencies" VALUES ('42', 'Algerian Dinar', 'DZD');
INSERT INTO "public"."supported_currencies" VALUES ('43', 'Estonian Kroon', 'EEK');
INSERT INTO "public"."supported_currencies" VALUES ('44', 'Egyptian Pound', 'EGP');
INSERT INTO "public"."supported_currencies" VALUES ('45', 'Eritrean Nakfa', 'ERN');
INSERT INTO "public"."supported_currencies" VALUES ('46', 'Ethiopian Birr', 'ETB');
INSERT INTO "public"."supported_currencies" VALUES ('47', 'Euro', 'EUR');
INSERT INTO "public"."supported_currencies" VALUES ('48', 'Fijian Dollar', 'FJD');
INSERT INTO "public"."supported_currencies" VALUES ('49', 'Falkland Islands Pound', 'FKP');
INSERT INTO "public"."supported_currencies" VALUES ('50', 'British Pound Sterling', 'GBP');
INSERT INTO "public"."supported_currencies" VALUES ('51', 'Georgian Lari', 'GEL');
INSERT INTO "public"."supported_currencies" VALUES ('52', 'Guernsey Pound', 'GGP');
INSERT INTO "public"."supported_currencies" VALUES ('53', 'Ghanaian Cedi', 'GHS');
INSERT INTO "public"."supported_currencies" VALUES ('54', 'Gibraltar Pound', 'GIP');
INSERT INTO "public"."supported_currencies" VALUES ('55', 'Gambian Dalasi', 'GMD');
INSERT INTO "public"."supported_currencies" VALUES ('56', 'Guinean Franc', 'GNF');
INSERT INTO "public"."supported_currencies" VALUES ('57', 'Guatemalan Quetzal', 'GTQ');
INSERT INTO "public"."supported_currencies" VALUES ('58', 'Guyanaese Dollar', 'GYD');
INSERT INTO "public"."supported_currencies" VALUES ('59', 'Hong Kong Dollar', 'HKD');
INSERT INTO "public"."supported_currencies" VALUES ('60', 'Honduran Lempira', 'HNL');
INSERT INTO "public"."supported_currencies" VALUES ('61', 'Croatian Kuna', 'HRK');
INSERT INTO "public"."supported_currencies" VALUES ('62', 'Haitian Gourde', 'HTG');
INSERT INTO "public"."supported_currencies" VALUES ('63', 'Hungarian Forint', 'HUF');
INSERT INTO "public"."supported_currencies" VALUES ('64', 'Indonesian Rupiah', 'IDR');
INSERT INTO "public"."supported_currencies" VALUES ('65', 'Israeli New Sheqel', 'ILS');
INSERT INTO "public"."supported_currencies" VALUES ('66', 'Manx pound', 'IMP');
INSERT INTO "public"."supported_currencies" VALUES ('67', 'Indian Rupee', 'INR');
INSERT INTO "public"."supported_currencies" VALUES ('68', 'Iraqi Dinar', 'IQD');
INSERT INTO "public"."supported_currencies" VALUES ('69', 'Iranian Rial', 'IRR');
INSERT INTO "public"."supported_currencies" VALUES ('70', 'Icelandic Króna', 'ISK');
INSERT INTO "public"."supported_currencies" VALUES ('71', 'Jersey Pound', 'JEP');
INSERT INTO "public"."supported_currencies" VALUES ('72', 'Jamaican Dollar', 'JMD');
INSERT INTO "public"."supported_currencies" VALUES ('73', 'Jordanian Dinar', 'JOD');
INSERT INTO "public"."supported_currencies" VALUES ('74', 'Japanese Yen', 'JPY');
INSERT INTO "public"."supported_currencies" VALUES ('75', 'Kenyan Shilling', 'KES');
INSERT INTO "public"."supported_currencies" VALUES ('76', 'Kyrgystani Som', 'KGS');
INSERT INTO "public"."supported_currencies" VALUES ('77', 'Cambodian Riel', 'KHR');
INSERT INTO "public"."supported_currencies" VALUES ('78', 'Comorian Franc', 'KMF');
INSERT INTO "public"."supported_currencies" VALUES ('79', 'North Korean Won', 'KPW');
INSERT INTO "public"."supported_currencies" VALUES ('80', 'South Korean Won', 'KRW');
INSERT INTO "public"."supported_currencies" VALUES ('81', 'Kuwaiti Dinar', 'KWD');
INSERT INTO "public"."supported_currencies" VALUES ('82', 'Cayman Islands Dollar', 'KYD');
INSERT INTO "public"."supported_currencies" VALUES ('83', 'Kazakhstani Tenge', 'KZT');
INSERT INTO "public"."supported_currencies" VALUES ('84', 'Laotian Kip', 'LAK');
INSERT INTO "public"."supported_currencies" VALUES ('85', 'Lebanese Pound', 'LBP');
INSERT INTO "public"."supported_currencies" VALUES ('86', 'Sri Lankan Rupee', 'LKR');
INSERT INTO "public"."supported_currencies" VALUES ('87', 'Liberian Dollar', 'LRD');
INSERT INTO "public"."supported_currencies" VALUES ('88', 'Lesotho Loti', 'LSL');
INSERT INTO "public"."supported_currencies" VALUES ('89', 'Lithuanian Litas', 'LTL');
INSERT INTO "public"."supported_currencies" VALUES ('90', 'Latvian Lats', 'LVL');
INSERT INTO "public"."supported_currencies" VALUES ('91', 'Libyan Dinar', 'LYD');
INSERT INTO "public"."supported_currencies" VALUES ('92', 'Moroccan Dirham', 'MAD');
INSERT INTO "public"."supported_currencies" VALUES ('93', 'Moldovan Leu', 'MDL');
INSERT INTO "public"."supported_currencies" VALUES ('94', 'Malagasy Ariary', 'MGA');
INSERT INTO "public"."supported_currencies" VALUES ('95', 'Macedonian Denar', 'MKD');
INSERT INTO "public"."supported_currencies" VALUES ('96', 'Myanma Kyat', 'MMK');
INSERT INTO "public"."supported_currencies" VALUES ('97', 'Mongolian Tugrik', 'MNT');
INSERT INTO "public"."supported_currencies" VALUES ('98', 'Macanese Pataca', 'MOP');
INSERT INTO "public"."supported_currencies" VALUES ('99', 'Mauritanian Ouguiya', 'MRO');
INSERT INTO "public"."supported_currencies" VALUES ('100', 'Mauritian Rupee', 'MUR');
INSERT INTO "public"."supported_currencies" VALUES ('101', 'Maldivian Rufiyaa', 'MVR');
INSERT INTO "public"."supported_currencies" VALUES ('102', 'Malawian Kwacha', 'MWK');
INSERT INTO "public"."supported_currencies" VALUES ('103', 'Mexican Peso', 'MXN');
INSERT INTO "public"."supported_currencies" VALUES ('104', 'Malaysian Ringgit', 'MYR');
INSERT INTO "public"."supported_currencies" VALUES ('105', 'Mozambican Metical', 'MZN');
INSERT INTO "public"."supported_currencies" VALUES ('106', 'Namibian Dollar', 'NAD');
INSERT INTO "public"."supported_currencies" VALUES ('107', 'Nigerian Naira', 'NGN');
INSERT INTO "public"."supported_currencies" VALUES ('108', 'Nicaraguan Córdoba', 'NIO');
INSERT INTO "public"."supported_currencies" VALUES ('109', 'Norwegian Krone', 'NOK');
INSERT INTO "public"."supported_currencies" VALUES ('110', 'Nepalese Rupee', 'NPR');
INSERT INTO "public"."supported_currencies" VALUES ('111', 'New Zealand Dollar', 'NZD');
INSERT INTO "public"."supported_currencies" VALUES ('112', 'Omani Rial', 'OMR');
INSERT INTO "public"."supported_currencies" VALUES ('113', 'Panamanian Balboa', 'PAB');
INSERT INTO "public"."supported_currencies" VALUES ('114', 'Peruvian Nuevo Sol', 'PEN');
INSERT INTO "public"."supported_currencies" VALUES ('115', 'Papua New Guinean Kina', 'PGK');
INSERT INTO "public"."supported_currencies" VALUES ('116', 'Philippine Peso', 'PHP');
INSERT INTO "public"."supported_currencies" VALUES ('117', 'Pakistani Rupee', 'PKR');
INSERT INTO "public"."supported_currencies" VALUES ('118', 'Polish Zloty', 'PLN');
INSERT INTO "public"."supported_currencies" VALUES ('119', 'Paraguayan Guarani', 'PYG');
INSERT INTO "public"."supported_currencies" VALUES ('120', 'Qatari Rial', 'QAR');
INSERT INTO "public"."supported_currencies" VALUES ('121', 'Romanian Leu', 'RON');
INSERT INTO "public"."supported_currencies" VALUES ('122', 'Serbian Dinar', 'RSD');
INSERT INTO "public"."supported_currencies" VALUES ('123', 'Russian Ruble', 'RUB');
INSERT INTO "public"."supported_currencies" VALUES ('124', 'Rwandan Franc', 'RWF');
INSERT INTO "public"."supported_currencies" VALUES ('125', 'Saudi Riyal', 'SAR');
INSERT INTO "public"."supported_currencies" VALUES ('126', 'Solomon Islands Dollar', 'SBD');
INSERT INTO "public"."supported_currencies" VALUES ('127', 'Seychellois Rupee', 'SCR');
INSERT INTO "public"."supported_currencies" VALUES ('128', 'Sudanese Pound', 'SDG');
INSERT INTO "public"."supported_currencies" VALUES ('129', 'Swedish Krona', 'SEK');
INSERT INTO "public"."supported_currencies" VALUES ('130', 'Singapore Dollar', 'SGD');
INSERT INTO "public"."supported_currencies" VALUES ('131', 'Saint Helena Pound', 'SHP');
INSERT INTO "public"."supported_currencies" VALUES ('132', 'Sierra Leonean Leone', 'SLL');
INSERT INTO "public"."supported_currencies" VALUES ('133', 'Somali Shilling', 'SOS');
INSERT INTO "public"."supported_currencies" VALUES ('134', 'Surinamese Dollar', 'SRD');
INSERT INTO "public"."supported_currencies" VALUES ('135', 'São Tomé and Príncipe Dobra', 'STD');
INSERT INTO "public"."supported_currencies" VALUES ('136', 'Salvadoran Colón', 'SVC');
INSERT INTO "public"."supported_currencies" VALUES ('137', 'Syrian Pound', 'SYP');
INSERT INTO "public"."supported_currencies" VALUES ('138', 'Swazi Lilangeni', 'SZL');
INSERT INTO "public"."supported_currencies" VALUES ('139', 'Thai Baht', 'THB');
INSERT INTO "public"."supported_currencies" VALUES ('140', 'Tajikistani Somoni', 'TJS');
INSERT INTO "public"."supported_currencies" VALUES ('141', 'Turkmenistani Manat', 'TMT');
INSERT INTO "public"."supported_currencies" VALUES ('142', 'Tunisian Dinar', 'TND');
INSERT INTO "public"."supported_currencies" VALUES ('143', 'Tongan Paʻanga', 'TOP');
INSERT INTO "public"."supported_currencies" VALUES ('144', 'Turkish Lira', 'TRY');
INSERT INTO "public"."supported_currencies" VALUES ('145', 'Trinidad and Tobago Dollar', 'TTD');
INSERT INTO "public"."supported_currencies" VALUES ('146', 'New Taiwan Dollar', 'TWD');
INSERT INTO "public"."supported_currencies" VALUES ('147', 'Tanzanian Shilling', 'TZS');
INSERT INTO "public"."supported_currencies" VALUES ('148', 'Ukrainian Hryvnia', 'UAH');
INSERT INTO "public"."supported_currencies" VALUES ('149', 'Ugandan Shilling', 'UGX');
INSERT INTO "public"."supported_currencies" VALUES ('150', 'United States Dollar', 'USD');
INSERT INTO "public"."supported_currencies" VALUES ('151', 'Uruguayan Peso', 'UYU');
INSERT INTO "public"."supported_currencies" VALUES ('152', 'Uzbekistan Som', 'UZS');
INSERT INTO "public"."supported_currencies" VALUES ('153', 'Venezuelan Bolívar Fuerte', 'VEF');
INSERT INTO "public"."supported_currencies" VALUES ('154', 'Vietnamese Dong', 'VND');
INSERT INTO "public"."supported_currencies" VALUES ('155', 'Vanuatu Vatu', 'VUV');
INSERT INTO "public"."supported_currencies" VALUES ('156', 'Samoan Tala', 'WST');
INSERT INTO "public"."supported_currencies" VALUES ('157', 'CFA Franc BEAC', 'XAF');
INSERT INTO "public"."supported_currencies" VALUES ('158', 'Silver (troy ounce)', 'XAG');
INSERT INTO "public"."supported_currencies" VALUES ('159', 'Gold (troy ounce)', 'XAU');
INSERT INTO "public"."supported_currencies" VALUES ('160', 'East Caribbean Dollar', 'XCD');
INSERT INTO "public"."supported_currencies" VALUES ('161', 'Special Drawing Rights', 'XDR');
INSERT INTO "public"."supported_currencies" VALUES ('162', 'CFA Franc BCEAO', 'XOF');
INSERT INTO "public"."supported_currencies" VALUES ('163', 'CFP Franc', 'XPF');
INSERT INTO "public"."supported_currencies" VALUES ('164', 'Yemeni Rial', 'YER');
INSERT INTO "public"."supported_currencies" VALUES ('165', 'South African Rand', 'ZAR');
INSERT INTO "public"."supported_currencies" VALUES ('166', 'Zambian Kwacha (pre-2013)', 'ZMK');
INSERT INTO "public"."supported_currencies" VALUES ('167', 'Zambian Kwacha', 'ZMW');
INSERT INTO "public"."supported_currencies" VALUES ('168', 'Zimbabwean Dollar', 'ZWL');
COMMIT;

-- ----------------------------
--  Primary key structure for table all_currencies
-- ----------------------------
ALTER TABLE "public"."all_currencies" ADD PRIMARY KEY ("id") NOT DEFERRABLE INITIALLY IMMEDIATE;

-- ----------------------------
--  Primary key structure for table country_codes
-- ----------------------------
ALTER TABLE "public"."country_codes" ADD PRIMARY KEY ("id") NOT DEFERRABLE INITIALLY IMMEDIATE;

-- ----------------------------
--  Primary key structure for table supported_currencies
-- ----------------------------
ALTER TABLE "public"."supported_currencies" ADD PRIMARY KEY ("id") NOT DEFERRABLE INITIALLY IMMEDIATE;

