# coding: utf-8
def populate(db):
    currency_data = []
    currency_data.append("INSERT INTO all_currencies VALUES ('1', 'Afghanistan', 'Afghan afghani', 'AFN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('2', 'Akrotiri and Dhekelia (UK)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('3', 'Aland Islands (Finland)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('4', 'Albania', 'Albanian lek', 'ALL');")
    currency_data.append("INSERT INTO all_currencies VALUES ('5', 'Algeria', 'Algerian dinar', 'DZD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('6', 'American Samoa (USA)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('7', 'Andorra', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('8', 'Angola', 'Angolan kwanza', 'AOA');")
    currency_data.append("INSERT INTO all_currencies VALUES ('9', 'Anguilla (UK)', 'East Caribbean dollar', 'XCD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('10', 'Antigua and Barbuda', 'East Caribbean dollar', 'XCD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('11', 'Argentina', 'Argentine peso', 'ARS');")
    currency_data.append("INSERT INTO all_currencies VALUES ('12', 'Armenia', 'Armenian dram', 'AMD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('13', 'Aruba (Netherlands)', 'Aruban florin', 'AWG');")
    currency_data.append("INSERT INTO all_currencies VALUES ('14', 'Ascension Island (UK)', 'Saint Helena pound', 'SHP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('15', 'Australia', 'Australian dollar', 'AUD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('16', 'Austria', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('17', 'Azerbaijan', 'Azerbaijani manat', 'AZN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('18', 'Bahamas', 'Bahamian dollar', 'BSD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('19', 'Bahrain', 'Bahraini dinar', 'BHD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('20', 'Bangladesh', 'Bangladeshi taka', 'BDT');")
    currency_data.append("INSERT INTO all_currencies VALUES ('21', 'Barbados', 'Barbadian dollar', 'BBD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('22', 'Belarus', 'Belarusian ruble', 'BYN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('23', 'Belgium', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('24', 'Belize', 'Belize dollar', 'BZD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('25', 'Benin', 'West African CFA franc', 'XOF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('26', 'Bermuda (UK)', 'Bermudian dollar', 'BMD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('27', 'Bhutan', 'Bhutanese ngultrum', 'BTN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('28', 'Bolivia', 'Bolivian boliviano', 'BOB');")
    currency_data.append("INSERT INTO all_currencies VALUES ('29', 'Bonaire (Netherlands)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('30', 'Bosnia and Herzegovina', 'Bosnia and Herzegovina convertible mark', 'BAM');")
    currency_data.append("INSERT INTO all_currencies VALUES ('31', 'Botswana', 'Botswana pula', 'BWP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('32', 'Brazil', 'Brazilian real', 'BRL');")
    currency_data.append("INSERT INTO all_currencies VALUES ('33', 'British Indian Ocean Territory (UK)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('34', 'British Virgin Islands (UK)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('35', 'Brunei', 'Brunei dollar', 'BND');")
    currency_data.append("INSERT INTO all_currencies VALUES ('36', 'Bulgaria', 'Bulgarian lev', 'BGN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('37', 'Burkina Faso', 'West African CFA franc', 'XOF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('38', 'Burundi', 'Burundi franc', 'BIF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('39', 'Cabo Verde', 'Cape Verdean escudo', 'CVE');")
    currency_data.append("INSERT INTO all_currencies VALUES ('40', 'Cambodia', 'Cambodian riel', 'KHR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('41', 'Cameroon', 'Central African CFA franc', 'XAF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('42', 'Canada', 'Canadian dollar', 'CAD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('43', 'Caribbean Netherlands (Netherlands)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('44', 'Cayman Islands (UK)', 'Cayman Islands dollar', 'KYD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('45', 'Central African Republic', 'Central African CFA franc', 'XAF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('46', 'Chad', 'Central African CFA franc', 'XAF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('47', 'Chile', 'Chilean peso', 'CLP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('48', 'China', 'Chinese Yuan Renminbi', 'CNY');")
    currency_data.append("INSERT INTO all_currencies VALUES ('49', 'Christmas Island (Australia)', 'Australian dollar', 'AUD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('50', 'Cocos (Keeling) Islands (Australia)', 'Australian dollar', 'AUD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('51', 'Colombia', 'Colombian peso', 'COP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('52', 'Comoros', 'Comorian franc', 'KMF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('53', 'Congo, Democratic Republic of the', 'Congolese franc', 'CDF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('54', 'Congo, Republic of the', 'Central African CFA franc', 'XAF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('55', 'Cook Islands (New Zealand)', 'Cook Islands dollar', 'none');")
    currency_data.append("INSERT INTO all_currencies VALUES ('56', 'Costa Rica', 'Costa Rican colon', 'CRC');")
    currency_data.append("INSERT INTO all_currencies VALUES ('57', 'Cote d''Ivoire', 'West African CFA franc', 'XOF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('58', 'Croatia', 'Croatian kuna', 'HRK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('59', 'Cuba', 'Cuban peso', 'CUP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('60', 'Curacao (Netherlands)', 'Netherlands Antillean guilder', 'ANG');")
    currency_data.append("INSERT INTO all_currencies VALUES ('61', 'Cyprus', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('62', 'Czech Republic', 'Czech koruna', 'CZK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('63', 'Denmark', 'Danish krone', 'DKK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('64', 'Djibouti', 'Djiboutian franc', 'DJF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('65', 'Dominica', 'East Caribbean dollar', 'XCD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('66', 'Dominican Republic', 'Dominican peso', 'DOP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('67', 'Ecuador', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('68', 'Egypt', 'Egyptian pound', 'EGP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('69', 'El Salvador', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('70', 'Equatorial Guinea', 'Central African CFA franc', 'XAF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('71', 'Eritrea', 'Eritrean nakfa', 'ERN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('72', 'Estonia', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('73', 'Ethiopia', 'Ethiopian birr', 'ETB');")
    currency_data.append("INSERT INTO all_currencies VALUES ('74', 'Falkland Islands (UK)', 'Falkland Islands pound', 'FKP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('75', 'Faroe Islands (Denmark)', 'Faroese krona', 'none');")
    currency_data.append("INSERT INTO all_currencies VALUES ('76', 'Fiji', 'Fijian dollar', 'FJD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('77', 'Finland', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('78', 'France', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('79', 'French Guiana (France)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('80', 'French Polynesia (France)', 'CFP franc', 'XPF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('81', 'Gabon', 'Central African CFA franc', 'XAF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('82', 'Gambia', 'Gambian dalasi', 'GMD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('83', 'Georgia', 'Georgian lari', 'GEL');")
    currency_data.append("INSERT INTO all_currencies VALUES ('84', 'Germany', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('85', 'Ghana', 'Ghanaian cedi', 'GHS');")
    currency_data.append("INSERT INTO all_currencies VALUES ('86', 'Gibraltar (UK)', 'Gibraltar pound', 'GIP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('87', 'Greece', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('88', 'Greenland (Denmark)', 'Danish krone', 'DKK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('89', 'Grenada', 'East Caribbean dollar', 'XCD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('90', 'Guadeloupe (France)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('91', 'Guam (USA)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('92', 'Guatemala', 'Guatemalan quetzal', 'GTQ');")
    currency_data.append("INSERT INTO all_currencies VALUES ('93', 'Guernsey (UK)', 'Guernsey Pound', 'GGP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('94', 'Guinea', 'Guinean franc', 'GNF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('95', 'Guinea-Bissau', 'West African CFA franc', 'XOF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('96', 'Guyana', 'Guyanese dollar', 'GYD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('97', 'Haiti', 'Haitian gourde', 'HTG');")
    currency_data.append("INSERT INTO all_currencies VALUES ('98', 'Honduras', 'Honduran lempira', 'HNL');")
    currency_data.append("INSERT INTO all_currencies VALUES ('99', 'Hong Kong (China)', 'Hong Kong dollar', 'HKD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('100', 'Hungary', 'Hungarian forint', 'HUF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('101', 'Iceland', 'Icelandic krona', 'ISK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('102', 'India', 'Indian rupee', 'INR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('103', 'Indonesia', 'Indonesian rupiah', 'IDR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('104', 'International Monetary Fund (IMF)', 'SDR (Special Drawing Right)', 'XDR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('105', 'Iran', 'Iranian rial', 'IRR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('106', 'Iraq', 'Iraqi dinar', 'IQD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('107', 'Ireland', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('108', 'Isle of Man (UK)', 'Manx pound', 'IMP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('109', 'Israel', 'Israeli new shekel', 'ILS');")
    currency_data.append("INSERT INTO all_currencies VALUES ('110', 'Italy', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('111', 'Jamaica', 'Jamaican dollar', 'JMD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('112', 'Japan', 'Japanese yen', 'JPY');")
    currency_data.append("INSERT INTO all_currencies VALUES ('113', 'Jersey (UK)', 'Jersey pound', 'JEP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('114', 'Jordan', 'Jordanian dinar', 'JOD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('115', 'Kazakhstan', 'Kazakhstani tenge', 'KZT');")
    currency_data.append("INSERT INTO all_currencies VALUES ('116', 'Kenya', 'Kenyan shilling', 'KES');")
    currency_data.append("INSERT INTO all_currencies VALUES ('117', 'Kiribati', 'Australian dollar', 'AUD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('118', 'Kosovo', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('119', 'Kuwait', 'Kuwaiti dinar', 'KWD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('120', 'Kyrgyzstan', 'Kyrgyzstani som', 'KGS');")
    currency_data.append("INSERT INTO all_currencies VALUES ('121', 'Laos', 'Lao kip', 'LAK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('122', 'Latvia', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('123', 'Lebanon', 'Lebanese pound', 'LBP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('124', 'Lesotho', 'Lesotho loti', 'LSL');")
    currency_data.append("INSERT INTO all_currencies VALUES ('125', 'Liberia', 'Liberian dollar', 'LRD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('126', 'Libya', 'Libyan dinar', 'LYD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('127', 'Liechtenstein', 'Swiss franc', 'CHF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('128', 'Lithuania', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('129', 'Luxembourg', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('130', 'Macau (China)', 'Macanese pataca', 'MOP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('131', 'Macedonia', 'Macedonian denar', 'MKD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('132', 'Madagascar', 'Malagasy ariary', 'MGA');")
    currency_data.append("INSERT INTO all_currencies VALUES ('133', 'Malawi', 'Malawian kwacha', 'MWK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('134', 'Malaysia', 'Malaysian ringgit', 'MYR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('135', 'Maldives', 'Maldivian rufiyaa', 'MVR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('136', 'Mali', 'West African CFA franc', 'XOF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('137', 'Malta', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('138', 'Marshall Islands', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('139', 'Martinique (France)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('140', 'Mauritania', 'Mauritanian ouguiya', 'MRO');")
    currency_data.append("INSERT INTO all_currencies VALUES ('141', 'Mauritius', 'Mauritian rupee', 'MUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('142', 'Mayotte (France)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('143', 'Mexico', 'Mexican peso', 'MXN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('144', 'Micronesia', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('145', 'Moldova', 'Moldovan leu', 'MDL');")
    currency_data.append("INSERT INTO all_currencies VALUES ('146', 'Monaco', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('147', 'Mongolia', 'Mongolian tugrik', 'MNT');")
    currency_data.append("INSERT INTO all_currencies VALUES ('148', 'Montenegro', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('149', 'Montserrat (UK)', 'East Caribbean dollar', 'XCD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('150', 'Morocco', 'Moroccan dirham', 'MAD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('151', 'Mozambique', 'Mozambican metical', 'MZN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('152', 'Myanmar (Burma)', 'Myanmar kyat', 'MMK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('153', 'Namibia', 'Namibian dollar', 'NAD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('154', 'Nauru', 'Australian dollar', 'AUD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('155', 'Nepal', 'Nepalese rupee', 'NPR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('156', 'Netherlands', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('157', 'New Caledonia (France)', 'CFP franc', 'XPF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('158', 'New Zealand', 'New Zealand dollar', 'NZD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('159', 'Nicaragua', 'Nicaraguan cordoba', 'NIO');")
    currency_data.append("INSERT INTO all_currencies VALUES ('160', 'Niger', 'West African CFA franc', 'XOF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('161', 'Nigeria', 'Nigerian naira', 'NGN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('162', 'Niue (New Zealand)', 'New Zealand dollar', 'NZD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('163', 'Norfolk Island (Australia)', 'Australian dollar', 'AUD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('164', 'Northern Mariana Islands (USA)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('165', 'North Korea', 'North Korean won', 'KPW');")
    currency_data.append("INSERT INTO all_currencies VALUES ('166', 'Norway', 'Norwegian krone', 'NOK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('167', 'Oman', 'Omani rial', 'OMR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('168', 'Pakistan', 'Pakistani rupee', 'PKR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('169', 'Palau', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('170', 'Palestine', 'Israeli new shekel', 'ILS');")
    currency_data.append("INSERT INTO all_currencies VALUES ('171', 'Panama', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('172', 'Papua New Guinea', 'Papua New Guinean kina', 'PGK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('173', 'Paraguay', 'Paraguayan guarani', 'PYG');")
    currency_data.append("INSERT INTO all_currencies VALUES ('174', 'Peru', 'Peruvian sol', 'PEN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('175', 'Philippines', 'Philippine peso', 'PHP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('176', 'Pitcairn Islands (UK)', 'New Zealand dollar', 'NZD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('177', 'Poland', 'Polish zloty', 'PLN');")
    currency_data.append("INSERT INTO all_currencies VALUES ('178', 'Portugal', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('179', 'Puerto Rico (USA)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('180', 'Qatar', 'Qatari riyal', 'QAR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('181', 'Reunion (France)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('182', 'Romania', 'Romanian leu', 'RON');")
    currency_data.append("INSERT INTO all_currencies VALUES ('183', 'Russia', 'Russian ruble', 'RUB');")
    currency_data.append("INSERT INTO all_currencies VALUES ('184', 'Rwanda', 'Rwandan franc', 'RWF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('185', 'Saba (Netherlands)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('186', 'Saint Barthelemy (France)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('187', 'Saint Helena (UK)', 'Saint Helena pound', 'SHP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('188', 'Saint Kitts and Nevis', 'East Caribbean dollar', 'XCD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('189', 'Saint Lucia', 'East Caribbean dollar', 'XCD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('190', 'Saint Martin (France)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('191', 'Saint Pierre and Miquelon (France)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('192', 'Saint Vincent and the Grenadines', 'East Caribbean dollar', 'XCD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('193', 'Samoa', 'Samoan tala', 'WST');")
    currency_data.append("INSERT INTO all_currencies VALUES ('194', 'San Marino', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('195', 'Sao Tome and Principe', 'Sao Tome and Principe dobra', 'STD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('196', 'Saudi Arabia', 'Saudi Arabian riyal', 'SAR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('197', 'Senegal', 'West African CFA franc', 'XOF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('198', 'Serbia', 'Serbian dinar', 'RSD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('199', 'Seychelles', 'Seychellois rupee', 'SCR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('200', 'Sierra Leone', 'Sierra Leonean leone', 'SLL');")
    currency_data.append("INSERT INTO all_currencies VALUES ('201', 'Singapore', 'Singapore dollar', 'SGD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('202', 'Sint Eustatius (Netherlands)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('203', 'Sint Maarten (Netherlands)', 'Netherlands Antillean guilder', 'ANG');")
    currency_data.append("INSERT INTO all_currencies VALUES ('204', 'Slovakia', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('205', 'Slovenia', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('206', 'Solomon Islands', 'Solomon Islands dollar', 'SBD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('207', 'Somalia', 'Somali shilling', 'SOS');")
    currency_data.append("INSERT INTO all_currencies VALUES ('208', 'South Africa', 'South African rand', 'ZAR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('209', 'South Georgia Island (UK)', 'Pound sterling', 'GBP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('210', 'South Korea', 'South Korean won', 'KRW');")
    currency_data.append("INSERT INTO all_currencies VALUES ('211', 'South Sudan', 'South Sudanese pound', 'SSP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('212', 'Spain', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('213', 'Sri Lanka', 'Sri Lankan rupee', 'LKR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('214', 'Sudan', 'Sudanese pound', 'SDG');")
    currency_data.append("INSERT INTO all_currencies VALUES ('215', 'Suriname', 'Surinamese dollar', 'SRD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('216', 'Svalbard and Jan Mayen (Norway)', 'Norwegian krone', 'NOK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('217', 'Swaziland', 'Swazi lilangeni', 'SZL');")
    currency_data.append("INSERT INTO all_currencies VALUES ('218', 'Sweden', 'Swedish krona', 'SEK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('219', 'Switzerland', 'Swiss franc', 'CHF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('220', 'Syria', 'Syrian pound', 'SYP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('221', 'Taiwan', 'New Taiwan dollar', 'TWD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('222', 'Tajikistan', 'Tajikistani somoni', 'TJS');")
    currency_data.append("INSERT INTO all_currencies VALUES ('223', 'Tanzania', 'Tanzanian shilling', 'TZS');")
    currency_data.append("INSERT INTO all_currencies VALUES ('224', 'Thailand', 'Thai baht', 'THB');")
    currency_data.append("INSERT INTO all_currencies VALUES ('225', 'Timor-Leste', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('226', 'Togo', 'West African CFA franc', 'XOF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('227', 'Tokelau (New Zealand)', 'New Zealand dollar', 'NZD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('228', 'Tonga', 'Tongan pa’anga', 'TOP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('229', 'Trinidad and Tobago', 'Trinidad and Tobago dollar', 'TTD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('230', 'Tristan da Cunha (UK)', 'Pound sterling', 'GBP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('231', 'Tunisia', 'Tunisian dinar', 'TND');")
    currency_data.append("INSERT INTO all_currencies VALUES ('232', 'Turkey', 'Turkish lira', 'TRY');")
    currency_data.append("INSERT INTO all_currencies VALUES ('233', 'Turkmenistan', 'Turkmen manat', 'TMT');")
    currency_data.append("INSERT INTO all_currencies VALUES ('234', 'Turks and Caicos Islands (UK)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('235', 'Tuvalu', 'Australian dollar', 'AUD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('236', 'Uganda', 'Ugandan shilling', 'UGX');")
    currency_data.append("INSERT INTO all_currencies VALUES ('237', 'Ukraine', 'Ukrainian hryvnia', 'UAH');")
    currency_data.append("INSERT INTO all_currencies VALUES ('238', 'United Arab Emirates', 'UAE dirham', 'AED');")
    currency_data.append("INSERT INTO all_currencies VALUES ('239', 'United Kingdom', 'Pound sterling', 'GBP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('240', 'United States of America', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('241', 'Uruguay', 'Uruguayan peso', 'UYU');")
    currency_data.append("INSERT INTO all_currencies VALUES ('242', 'US Virgin Islands (USA)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('243', 'Uzbekistan', 'Uzbekistani som', 'UZS');")
    currency_data.append("INSERT INTO all_currencies VALUES ('244', 'Vanuatu', 'Vanuatu vatu', 'VUV');")
    currency_data.append("INSERT INTO all_currencies VALUES ('245', 'Vatican City (Holy See)', 'European euro', 'EUR');")
    currency_data.append("INSERT INTO all_currencies VALUES ('246', 'Venezuela', 'Venezuelan bolivar', 'VEF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('247', 'Vietnam', 'Vietnamese dong', 'VND');")
    currency_data.append("INSERT INTO all_currencies VALUES ('248', 'Wake Island (USA)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('249', 'Wallis and Futuna (France)', 'CFP franc', 'XPF');")
    currency_data.append("INSERT INTO all_currencies VALUES ('250', 'Yemen', 'Yemeni rial', 'YER');")
    currency_data.append("INSERT INTO all_currencies VALUES ('251', 'Zambia', 'Zambian kwacha', 'ZMW');")
    currency_data.append("INSERT INTO all_currencies VALUES ('252', 'Zimbabwe', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('253', 'UK (Dfid and other)', 'Pound sterling', 'GBP');")
    currency_data.append("INSERT INTO all_currencies VALUES ('254', 'Sweden (Sida and other)', 'Swedish krona', 'SEK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('255', 'Norway (Norad and other)', 'Norwegian krone', 'NOK');")
    currency_data.append("INSERT INTO all_currencies VALUES ('256', 'US (USAID and other)', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('258', 'United Nations', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('259', 'World Bank', 'United States dollar', 'USD');")
    currency_data.append("INSERT INTO all_currencies VALUES ('257', 'European Union or Commission', 'European euro', 'EUR');")
  
    


    currency_data.append("INSERT INTO country_codes VALUES ('1', 'Afghanistan', 'AF');")
    currency_data.append("INSERT INTO country_codes VALUES ('2', 'Akrotiri Sovereign Base Area', 'AX');")
    currency_data.append("INSERT INTO country_codes VALUES ('3', 'Albania', 'AL');")
    currency_data.append("INSERT INTO country_codes VALUES ('4', 'Algeria', 'AG');")
    currency_data.append("INSERT INTO country_codes VALUES ('5', 'American Samoa', 'AQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('6', 'Andorra', 'AN');")
    currency_data.append("INSERT INTO country_codes VALUES ('7', 'Angola', 'AO');")
    currency_data.append("INSERT INTO country_codes VALUES ('8', 'Anguilla', 'AV');")
    currency_data.append("INSERT INTO country_codes VALUES ('9', 'Antarctica', 'AY');")
    currency_data.append("INSERT INTO country_codes VALUES ('10', 'Antigua and Barbuda', 'AC');")
    currency_data.append("INSERT INTO country_codes VALUES ('11', 'Argentina', 'AR');")
    currency_data.append("INSERT INTO country_codes VALUES ('12', 'Armenia', 'AM');")
    currency_data.append("INSERT INTO country_codes VALUES ('13', 'Aruba', 'AA');")
    currency_data.append("INSERT INTO country_codes VALUES ('14', 'Ashmore and Cartier Islands', 'AT');")
    currency_data.append("INSERT INTO country_codes VALUES ('15', 'Australia', 'AS');")
    currency_data.append("INSERT INTO country_codes VALUES ('16', 'Austria', 'AU');")
    currency_data.append("INSERT INTO country_codes VALUES ('17', 'Azerbaijan', 'AJ');")
    currency_data.append("INSERT INTO country_codes VALUES ('18', 'Bahamas', 'BF');")
    currency_data.append("INSERT INTO country_codes VALUES ('19', 'Bahrain', 'BA');")
    currency_data.append("INSERT INTO country_codes VALUES ('20', 'Baker Island', 'FQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('21', 'Bangladesh', 'BG');")
    currency_data.append("INSERT INTO country_codes VALUES ('22', 'Barbados', 'BB');")
    currency_data.append("INSERT INTO country_codes VALUES ('23', 'Bassas da India', 'BS');")
    currency_data.append("INSERT INTO country_codes VALUES ('24', 'Belarus', 'BO');")
    currency_data.append("INSERT INTO country_codes VALUES ('25', 'Belgium', 'BE');")
    currency_data.append("INSERT INTO country_codes VALUES ('26', 'Belize', 'BH');")
    currency_data.append("INSERT INTO country_codes VALUES ('27', 'Benin', 'BN');")
    currency_data.append("INSERT INTO country_codes VALUES ('28', 'Bermuda', 'BD');")
    currency_data.append("INSERT INTO country_codes VALUES ('29', 'Bhutan', 'BT');")
    currency_data.append("INSERT INTO country_codes VALUES ('30', 'Bolivia', 'BL');")
    currency_data.append("INSERT INTO country_codes VALUES ('31', 'Bosnia-Herzegovina', 'BK');")
    currency_data.append("INSERT INTO country_codes VALUES ('32', 'Botswana', 'BC');")
    currency_data.append("INSERT INTO country_codes VALUES ('33', 'Bouvet Island', 'BV');")
    currency_data.append("INSERT INTO country_codes VALUES ('34', 'Brazil', 'BR');")
    currency_data.append("INSERT INTO country_codes VALUES ('35', 'British Indian Ocean Territory', 'IO');")
    currency_data.append("INSERT INTO country_codes VALUES ('36', 'British Virgin Islands', 'VI');")
    currency_data.append("INSERT INTO country_codes VALUES ('37', 'Brunei', 'BX');")
    currency_data.append("INSERT INTO country_codes VALUES ('38', 'Bulgaria', 'BU');")
    currency_data.append("INSERT INTO country_codes VALUES ('39', 'Burkina Faso', 'UV');")
    currency_data.append("INSERT INTO country_codes VALUES ('40', 'Burundi', 'BY');")
    currency_data.append("INSERT INTO country_codes VALUES ('41', 'Cambodia', 'CB');")
    currency_data.append("INSERT INTO country_codes VALUES ('42', 'Cameroon', 'CM');")
    currency_data.append("INSERT INTO country_codes VALUES ('43', 'Canada', 'CA');")
    currency_data.append("INSERT INTO country_codes VALUES ('44', 'Cape Verde', 'CV');")
    currency_data.append("INSERT INTO country_codes VALUES ('45', 'Cayman Islands', 'CJ');")
    currency_data.append("INSERT INTO country_codes VALUES ('46', 'Central African Republic', 'CT');")
    currency_data.append("INSERT INTO country_codes VALUES ('47', 'Chad', 'CD');")
    currency_data.append("INSERT INTO country_codes VALUES ('48', 'Chile', 'CI');")
    currency_data.append("INSERT INTO country_codes VALUES ('49', 'China', 'CH');")
    currency_data.append("INSERT INTO country_codes VALUES ('50', 'Christmas Island', 'KT');")
    currency_data.append("INSERT INTO country_codes VALUES ('51', 'Clipperton Island', 'IP');")
    currency_data.append("INSERT INTO country_codes VALUES ('52', 'Cocos Keeling Islands', 'CK');")
    currency_data.append("INSERT INTO country_codes VALUES ('53', 'Colombia', 'CO');")
    currency_data.append("INSERT INTO country_codes VALUES ('54', 'Comoros', 'CN');")
    currency_data.append("INSERT INTO country_codes VALUES ('55', 'Congo', 'CF');")
    currency_data.append("INSERT INTO country_codes VALUES ('56', 'Cook Islands', 'CW');")
    currency_data.append("INSERT INTO country_codes VALUES ('57', 'Coral Sea Islands', 'CR');")
    currency_data.append("INSERT INTO country_codes VALUES ('58', 'Costa Rica', 'CS');")
    currency_data.append("INSERT INTO country_codes VALUES ('59', 'Cote dIvoire', 'IV');")
    currency_data.append("INSERT INTO country_codes VALUES ('60', 'Croatia', 'HR');")
    currency_data.append("INSERT INTO country_codes VALUES ('61', 'Cuba', 'CU');")
    currency_data.append("INSERT INTO country_codes VALUES ('62', 'Cyprus', 'CY');")
    currency_data.append("INSERT INTO country_codes VALUES ('63', 'Czech Republic', 'EZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('64', 'Czechoslovakia', 'LO');")
    currency_data.append("INSERT INTO country_codes VALUES ('65', 'Democratic Republic of the Congo', 'CG');")
    currency_data.append("INSERT INTO country_codes VALUES ('66', 'Denmark', 'DA');")
    currency_data.append("INSERT INTO country_codes VALUES ('67', 'Dhekelia Sovereign Base Area', 'DX');")
    currency_data.append("INSERT INTO country_codes VALUES ('68', 'Djibouti', 'DJ');")
    currency_data.append("INSERT INTO country_codes VALUES ('69', 'Dominica', 'DO');")
    currency_data.append("INSERT INTO country_codes VALUES ('70', 'Dominican Republic', 'DR');")
    currency_data.append("INSERT INTO country_codes VALUES ('71', 'East Timor', 'TT');")
    currency_data.append("INSERT INTO country_codes VALUES ('72', 'Ecuador', 'EC');")
    currency_data.append("INSERT INTO country_codes VALUES ('73', 'Egypt', 'EG');")
    currency_data.append("INSERT INTO country_codes VALUES ('74', 'El Salvador', 'ES');")
    currency_data.append("INSERT INTO country_codes VALUES ('75', 'Equatorial Guinea', 'GV');")
    currency_data.append("INSERT INTO country_codes VALUES ('76', 'Equatorial Guinea', 'EK');")
    currency_data.append("INSERT INTO country_codes VALUES ('77', 'Eritrea', 'ER');")
    currency_data.append("INSERT INTO country_codes VALUES ('78', 'Estonia', 'EN');")
    currency_data.append("INSERT INTO country_codes VALUES ('79', 'Ethiopia', 'ET');")
    currency_data.append("INSERT INTO country_codes VALUES ('80', 'Etorofu', 'PJ');")
    currency_data.append("INSERT INTO country_codes VALUES ('81', 'Europa Island', 'EU');")
    currency_data.append("INSERT INTO country_codes VALUES ('82', 'Falkland Islands Islas Malvinas', 'FK');")
    currency_data.append("INSERT INTO country_codes VALUES ('83', 'Faroe Islands', 'FO');")
    currency_data.append("INSERT INTO country_codes VALUES ('84', 'Fiji', 'FJ');")
    currency_data.append("INSERT INTO country_codes VALUES ('85', 'Finland', 'FI');")
    currency_data.append("INSERT INTO country_codes VALUES ('86', 'France', 'FR');")
    currency_data.append("INSERT INTO country_codes VALUES ('87', 'French Guiana', 'FG');")
    currency_data.append("INSERT INTO country_codes VALUES ('88', 'French Polynesia', 'FP');")
    currency_data.append("INSERT INTO country_codes VALUES ('89', 'French Southern and Antarctic Lands', 'FS');")
    currency_data.append("INSERT INTO country_codes VALUES ('90', 'Gabon', 'GB');")
    currency_data.append("INSERT INTO country_codes VALUES ('91', 'Gambia', 'GA');")
    currency_data.append("INSERT INTO country_codes VALUES ('92', 'Gaza Strip', 'GZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('93', 'Georgia', 'GG');")
    currency_data.append("INSERT INTO country_codes VALUES ('94', 'Germany', 'GM');")
    currency_data.append("INSERT INTO country_codes VALUES ('95', 'Ghana', 'GH');")
    currency_data.append("INSERT INTO country_codes VALUES ('96', 'Gibraltar', 'GI');")
    currency_data.append("INSERT INTO country_codes VALUES ('97', 'Glorioso Islands', 'GO');")
    currency_data.append("INSERT INTO country_codes VALUES ('98', 'Greece', 'GR');")
    currency_data.append("INSERT INTO country_codes VALUES ('99', 'Greenland', 'GL');")
    currency_data.append("INSERT INTO country_codes VALUES ('100', 'Grenada', 'GJ');")
    currency_data.append("INSERT INTO country_codes VALUES ('101', 'Guadeloupe', 'GP');")
    currency_data.append("INSERT INTO country_codes VALUES ('102', 'Guam', 'GQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('103', 'Guatemala', 'GT');")
    currency_data.append("INSERT INTO country_codes VALUES ('104', 'Guernsey', 'GK');")
    currency_data.append("INSERT INTO country_codes VALUES ('105', 'Guinea-Bissau', 'PU');")
    currency_data.append("INSERT INTO country_codes VALUES ('106', 'Guyana', 'GY');")
    currency_data.append("INSERT INTO country_codes VALUES ('107', 'Haiti', 'HA');")
    currency_data.append("INSERT INTO country_codes VALUES ('108', 'Heard Island and McDonald Islands', 'HM');")
    currency_data.append("INSERT INTO country_codes VALUES ('109', 'Honduras', 'HO');")
    currency_data.append("INSERT INTO country_codes VALUES ('110', 'Hong Kong', 'HK');")
    currency_data.append("INSERT INTO country_codes VALUES ('111', 'Howland Island', 'HQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('112', 'Hungary', 'HU');")
    currency_data.append("INSERT INTO country_codes VALUES ('113', 'Iceland', 'IC');")
    currency_data.append("INSERT INTO country_codes VALUES ('114', 'India', 'IN');")
    currency_data.append("INSERT INTO country_codes VALUES ('115', 'Indonesia', 'ID');")
    currency_data.append("INSERT INTO country_codes VALUES ('116', 'Iran', 'IR');")
    currency_data.append("INSERT INTO country_codes VALUES ('117', 'Iraq', 'IZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('118', 'Ireland', 'EI');")
    currency_data.append("INSERT INTO country_codes VALUES ('119', 'Isle of Man', 'IM');")
    currency_data.append("INSERT INTO country_codes VALUES ('120', 'Israel', 'IS');")
    currency_data.append("INSERT INTO country_codes VALUES ('121', 'Italy', 'IT');")
    currency_data.append("INSERT INTO country_codes VALUES ('122', 'Jamaica', 'JM');")
    currency_data.append("INSERT INTO country_codes VALUES ('123', 'Jan Mayen', 'JN');")
    currency_data.append("INSERT INTO country_codes VALUES ('124', 'Japan', 'JA');")
    currency_data.append("INSERT INTO country_codes VALUES ('125', 'Jarvis Island', 'DQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('126', 'Jersey', 'JE');")
    currency_data.append("INSERT INTO country_codes VALUES ('127', 'Johnston Atoll', 'JQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('128', 'Jordan', 'JO');")
    currency_data.append("INSERT INTO country_codes VALUES ('129', 'Juan de Nova Island', 'JU');")
    currency_data.append("INSERT INTO country_codes VALUES ('130', 'Kazakhstan', 'KZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('131', 'Kenya', 'KE');")
    currency_data.append("INSERT INTO country_codes VALUES ('132', 'Kingman Reef', 'KQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('133', 'Kiribati', 'KR');")
    currency_data.append("INSERT INTO country_codes VALUES ('134', 'Kosovo', 'KV');")
    currency_data.append("INSERT INTO country_codes VALUES ('135', 'Kuwait', 'KU');")
    currency_data.append("INSERT INTO country_codes VALUES ('136', 'Kyrgyzstan', 'KG');")
    currency_data.append("INSERT INTO country_codes VALUES ('137', 'Laos', 'LA');")
    currency_data.append("INSERT INTO country_codes VALUES ('138', 'Latvia', 'LG');")
    currency_data.append("INSERT INTO country_codes VALUES ('139', 'Lebanon', 'LE');")
    currency_data.append("INSERT INTO country_codes VALUES ('140', 'Lesotho', 'LT');")
    currency_data.append("INSERT INTO country_codes VALUES ('141', 'Liberia', 'LI');")
    currency_data.append("INSERT INTO country_codes VALUES ('142', 'Libya', 'LY');")
    currency_data.append("INSERT INTO country_codes VALUES ('143', 'Liechtenstein', 'LS');")
    currency_data.append("INSERT INTO country_codes VALUES ('144', 'Lithuania', 'LH');")
    currency_data.append("INSERT INTO country_codes VALUES ('145', 'Luxembourg', 'LU');")
    currency_data.append("INSERT INTO country_codes VALUES ('146', 'Macau', 'MC');")
    currency_data.append("INSERT INTO country_codes VALUES ('147', 'Macedonia', 'MK');")
    currency_data.append("INSERT INTO country_codes VALUES ('148', 'Madagascar', 'MA');")
    currency_data.append("INSERT INTO country_codes VALUES ('149', 'Malawi', 'MI');")
    currency_data.append("INSERT INTO country_codes VALUES ('150', 'Malaysia', 'MY');")
    currency_data.append("INSERT INTO country_codes VALUES ('151', 'Maldives', 'MV');")
    currency_data.append("INSERT INTO country_codes VALUES ('152', 'Mali', 'ML');")
    currency_data.append("INSERT INTO country_codes VALUES ('153', 'Malta', 'MT');")
    currency_data.append("INSERT INTO country_codes VALUES ('154', 'Marshall Islands', 'RM');")
    currency_data.append("INSERT INTO country_codes VALUES ('155', 'Martinique', 'MB');")
    currency_data.append("INSERT INTO country_codes VALUES ('156', 'Mauritania', 'MR');")
    currency_data.append("INSERT INTO country_codes VALUES ('157', 'Mauritius', 'MP');")
    currency_data.append("INSERT INTO country_codes VALUES ('158', 'Mayotte', 'MF');")
    currency_data.append("INSERT INTO country_codes VALUES ('159', 'Mexico', 'MX');")
    currency_data.append("INSERT INTO country_codes VALUES ('160', 'Micronesia', 'FM');")
    currency_data.append("INSERT INTO country_codes VALUES ('161', 'Midway Islands', 'MQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('162', 'Moldova', 'MD');")
    currency_data.append("INSERT INTO country_codes VALUES ('163', 'Monaco', 'MN');")
    currency_data.append("INSERT INTO country_codes VALUES ('164', 'Mongolia', 'MG');")
    currency_data.append("INSERT INTO country_codes VALUES ('165', 'Montenegro', 'MJ');")
    currency_data.append("INSERT INTO country_codes VALUES ('166', 'Montserrat', 'MH');")
    currency_data.append("INSERT INTO country_codes VALUES ('167', 'Morocco', 'MO');")
    currency_data.append("INSERT INTO country_codes VALUES ('168', 'Mozambique', 'MZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('169', 'Myanmar', 'BM');")
    currency_data.append("INSERT INTO country_codes VALUES ('170', 'Namibia', 'WA');")
    currency_data.append("INSERT INTO country_codes VALUES ('171', 'Nauru', 'NR');")
    currency_data.append("INSERT INTO country_codes VALUES ('172', 'Navassa Island', 'BQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('173', 'Nepal', 'NP');")
    currency_data.append("INSERT INTO country_codes VALUES ('174', 'Netherlands', 'NL');")
    currency_data.append("INSERT INTO country_codes VALUES ('175', 'Netherlands Antilles', 'NT');")
    currency_data.append("INSERT INTO country_codes VALUES ('176', 'New Caledonia', 'NC');")
    currency_data.append("INSERT INTO country_codes VALUES ('177', 'New Zealand', 'NZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('178', 'Nicaragua', 'NU');")
    currency_data.append("INSERT INTO country_codes VALUES ('179', 'Niger', 'NG');")
    currency_data.append("INSERT INTO country_codes VALUES ('180', 'Nigeria', 'NI');")
    currency_data.append("INSERT INTO country_codes VALUES ('181', 'Niue', 'NE');")
    currency_data.append("INSERT INTO country_codes VALUES ('182', 'No Mans Land', 'NM');")
    currency_data.append("INSERT INTO country_codes VALUES ('183', 'Norfolk Island', 'NF');")
    currency_data.append("INSERT INTO country_codes VALUES ('184', 'North Korea', 'KN');")
    currency_data.append("INSERT INTO country_codes VALUES ('185', 'Northern Mariana Islands', 'CQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('186', 'Norway', 'NO');")
    currency_data.append("INSERT INTO country_codes VALUES ('187', 'Oceans', 'OS');")
    currency_data.append("INSERT INTO country_codes VALUES ('188', 'Oman', 'MU');")
    currency_data.append("INSERT INTO country_codes VALUES ('189', 'Pakistan', 'PK');")
    currency_data.append("INSERT INTO country_codes VALUES ('190', 'Palau', 'PS');")
    currency_data.append("INSERT INTO country_codes VALUES ('191', 'Palmyra Atoll', 'LQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('192', 'Panama', 'PM');")
    currency_data.append("INSERT INTO country_codes VALUES ('193', 'Papua New Guinea', 'PP');")
    currency_data.append("INSERT INTO country_codes VALUES ('194', 'Paracel Islands', 'PF');")
    currency_data.append("INSERT INTO country_codes VALUES ('195', 'Paraguay', 'PA');")
    currency_data.append("INSERT INTO country_codes VALUES ('196', 'Peru', 'PE');")
    currency_data.append("INSERT INTO country_codes VALUES ('197', 'Philippines', 'RP');")
    currency_data.append("INSERT INTO country_codes VALUES ('198', 'Pitcairn Islands', 'PC');")
    currency_data.append("INSERT INTO country_codes VALUES ('199', 'Poland', 'PL');")
    currency_data.append("INSERT INTO country_codes VALUES ('200', 'Portugal', 'PO');")
    currency_data.append("INSERT INTO country_codes VALUES ('201', 'Puerto Rico', 'RQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('202', 'Qatar', 'QA');")
    currency_data.append("INSERT INTO country_codes VALUES ('203', 'Reunion', 'RE');")
    currency_data.append("INSERT INTO country_codes VALUES ('204', 'Romania', 'RO');")
    currency_data.append("INSERT INTO country_codes VALUES ('205', 'Russia', 'RS');")
    currency_data.append("INSERT INTO country_codes VALUES ('206', 'Rwanda', 'RW');")
    currency_data.append("INSERT INTO country_codes VALUES ('207', 'Saint Helena', 'SH');")
    currency_data.append("INSERT INTO country_codes VALUES ('208', 'Saint Kitts and Nevis', 'SC');")
    currency_data.append("INSERT INTO country_codes VALUES ('209', 'Saint Lucia', 'ST');")
    currency_data.append("INSERT INTO country_codes VALUES ('210', 'Saint Martin', 'RN');")
    currency_data.append("INSERT INTO country_codes VALUES ('211', 'Saint Pierre and Miquelon', 'SB');")
    currency_data.append("INSERT INTO country_codes VALUES ('212', 'Saint Vincent and the Grenadines', 'VC');")
    currency_data.append("INSERT INTO country_codes VALUES ('213', 'Saint-Barthelemy Island', 'TB');")
    currency_data.append("INSERT INTO country_codes VALUES ('214', 'Samoa', 'WS');")
    currency_data.append("INSERT INTO country_codes VALUES ('215', 'San Marino', 'SM');")
    currency_data.append("INSERT INTO country_codes VALUES ('216', 'Sao Tome and Principe', 'TP');")
    currency_data.append("INSERT INTO country_codes VALUES ('217', 'Saudi Arabia', 'SA');")
    currency_data.append("INSERT INTO country_codes VALUES ('218', 'Senegal', 'SG');")
    currency_data.append("INSERT INTO country_codes VALUES ('219', 'Serbia', 'RI');")
    currency_data.append("INSERT INTO country_codes VALUES ('220', 'Seychelles', 'SE');")
    currency_data.append("INSERT INTO country_codes VALUES ('221', 'Sierra Leone', 'SL');")
    currency_data.append("INSERT INTO country_codes VALUES ('222', 'Singapore', 'SN');")
    currency_data.append("INSERT INTO country_codes VALUES ('223', 'Slovenia', 'SI');")
    currency_data.append("INSERT INTO country_codes VALUES ('224', 'Solomon Islands', 'BP');")
    currency_data.append("INSERT INTO country_codes VALUES ('225', 'Somalia', 'SO');")
    currency_data.append("INSERT INTO country_codes VALUES ('226', 'South Africa', 'SF');")
    currency_data.append("INSERT INTO country_codes VALUES ('227', 'South Georgia and the South Sandwich Islands', 'SX');")
    currency_data.append("INSERT INTO country_codes VALUES ('228', 'South Korea', 'KS');")
    currency_data.append("INSERT INTO country_codes VALUES ('229', 'South Sudan', 'OD');")
    currency_data.append("INSERT INTO country_codes VALUES ('230', 'Spain', 'SP');")
    currency_data.append("INSERT INTO country_codes VALUES ('231', 'Spratly Islands', 'PG');")
    currency_data.append("INSERT INTO country_codes VALUES ('232', 'Sri Lanka', 'CE');")
    currency_data.append("INSERT INTO country_codes VALUES ('233', 'Sudan', 'SU');")
    currency_data.append("INSERT INTO country_codes VALUES ('234', 'Suriname', 'NS');")
    currency_data.append("INSERT INTO country_codes VALUES ('235', 'Svalbard', 'SV');")
    currency_data.append("INSERT INTO country_codes VALUES ('236', 'Swaziland', 'WZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('237', 'Sweden', 'SW');")
    currency_data.append("INSERT INTO country_codes VALUES ('238', 'Switzerland', 'SZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('239', 'Syria', 'SY');")
    currency_data.append("INSERT INTO country_codes VALUES ('240', 'Taiwan', 'TW');")
    currency_data.append("INSERT INTO country_codes VALUES ('241', 'Tajikistan', 'TI');")
    currency_data.append("INSERT INTO country_codes VALUES ('242', 'Tanzania', 'TZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('243', 'Thailand', 'TH');")
    currency_data.append("INSERT INTO country_codes VALUES ('244', 'Togo', 'TO');")
    currency_data.append("INSERT INTO country_codes VALUES ('245', 'Tokelau', 'TL');")
    currency_data.append("INSERT INTO country_codes VALUES ('246', 'Tonga', 'TN');")
    currency_data.append("INSERT INTO country_codes VALUES ('247', 'Trinidad and Tobago', 'TD');")
    currency_data.append("INSERT INTO country_codes VALUES ('248', 'Tromelin Island', 'TE');")
    currency_data.append("INSERT INTO country_codes VALUES ('249', 'Tunisia', 'TS');")
    currency_data.append("INSERT INTO country_codes VALUES ('250', 'Turkey', 'TU');")
    currency_data.append("INSERT INTO country_codes VALUES ('251', 'Turkmenistan', 'TX');")
    currency_data.append("INSERT INTO country_codes VALUES ('252', 'Turks and Caicos Islands', 'TK');")
    currency_data.append("INSERT INTO country_codes VALUES ('253', 'Tuvalu', 'TV');")
    currency_data.append("INSERT INTO country_codes VALUES ('254', 'Uganda', 'UG');")
    currency_data.append("INSERT INTO country_codes VALUES ('255', 'Ukraine', 'UP');")
    currency_data.append("INSERT INTO country_codes VALUES ('256', 'Undersea Features', 'UF');")
    currency_data.append("INSERT INTO country_codes VALUES ('257', 'Undesignated Sovereignty', 'UU');")
    currency_data.append("INSERT INTO country_codes VALUES ('258', 'United Arab Emirates', 'AE');")
    currency_data.append("INSERT INTO country_codes VALUES ('259', 'United Kingdom', 'UK');")
    currency_data.append("INSERT INTO country_codes VALUES ('260', 'United States', 'US');")
    currency_data.append("INSERT INTO country_codes VALUES ('261', 'Uruguay', 'UY');")
    currency_data.append("INSERT INTO country_codes VALUES ('262', 'Uzbekistan', 'UZ');")
    currency_data.append("INSERT INTO country_codes VALUES ('263', 'Vanuatu', 'NH');")
    currency_data.append("INSERT INTO country_codes VALUES ('264', 'Vatican City', 'VT');")
    currency_data.append("INSERT INTO country_codes VALUES ('265', 'Venezuela', 'VE');")
    currency_data.append("INSERT INTO country_codes VALUES ('266', 'Vietnam', 'VM');")
    currency_data.append("INSERT INTO country_codes VALUES ('267', 'Virgin Islands', 'VQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('268', 'Wake Island', 'WQ');")
    currency_data.append("INSERT INTO country_codes VALUES ('269', 'Wallis and Futuna', 'WF');")
    currency_data.append("INSERT INTO country_codes VALUES ('270', 'West Bank', 'WE');")
    currency_data.append("INSERT INTO country_codes VALUES ('271', 'Western Sahara', 'WI');")
    currency_data.append("INSERT INTO country_codes VALUES ('272', 'Yemen', 'YM');")
    currency_data.append("INSERT INTO country_codes VALUES ('273', 'Zambia', 'ZA');")
    currency_data.append("INSERT INTO country_codes VALUES ('274', 'Zimbabwe', 'ZI');")

    currency_data.append("INSERT INTO supported_currencies VALUES ('1', 'United Arab Emirates Dirham', 'AED');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('2', 'Afghan Afghani', 'AFN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('3', 'Albanian Lek', 'ALL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('4', 'Armenian Dram', 'AMD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('5', 'Netherlands Antillean Guilder', 'ANG');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('6', 'Angolan Kwanza', 'AOA');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('7', 'Argentine Peso', 'ARS');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('8', 'Australian Dollar', 'AUD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('9', 'Aruban Florin', 'AWG');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('10', 'Azerbaijani Manat', 'AZN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('11', 'Bosnia-Herzegovina Convertible Mark', 'BAM');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('12', 'Barbadian Dollar', 'BBD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('13', 'Bangladeshi Taka', 'BDT');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('14', 'Bulgarian Lev', 'BGN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('15', 'Bahraini Dinar', 'BHD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('16', 'Burundian Franc', 'BIF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('17', 'Bermudan Dollar', 'BMD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('18', 'Brunei Dollar', 'BND');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('19', 'Bolivian Boliviano', 'BOB');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('20', 'Brazilian Real', 'BRL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('21', 'Bahamian Dollar', 'BSD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('22', 'Bitcoin', 'BTC');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('23', 'Bhutanese Ngultrum', 'BTN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('24', 'Botswanan Pula', 'BWP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('25', 'Belarusian Ruble', 'BYR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('26', 'Belize Dollar', 'BZD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('27', 'Canadian Dollar', 'CAD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('28', 'Congolese Franc', 'CDF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('29', 'Swiss Franc', 'CHF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('30', 'Chilean Unit of Account (UF)', 'CLF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('31', 'Chilean Peso', 'CLP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('32', 'Chinese Yuan', 'CNY');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('33', 'Colombian Peso', 'COP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('34', 'Costa Rican Colón', 'CRC');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('35', 'Cuban Convertible Peso', 'CUC');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('36', 'Cuban Peso', 'CUP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('37', 'Cape Verdean Escudo', 'CVE');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('38', 'Czech Republic Koruna', 'CZK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('39', 'Djiboutian Franc', 'DJF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('40', 'Danish Krone', 'DKK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('41', 'Dominican Peso', 'DOP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('42', 'Algerian Dinar', 'DZD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('43', 'Estonian Kroon', 'EEK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('44', 'Egyptian Pound', 'EGP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('45', 'Eritrean Nakfa', 'ERN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('46', 'Ethiopian Birr', 'ETB');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('47', 'Euro', 'EUR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('48', 'Fijian Dollar', 'FJD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('49', 'Falkland Islands Pound', 'FKP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('50', 'British Pound Sterling', 'GBP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('51', 'Georgian Lari', 'GEL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('52', 'Guernsey Pound', 'GGP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('53', 'Ghanaian Cedi', 'GHS');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('54', 'Gibraltar Pound', 'GIP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('55', 'Gambian Dalasi', 'GMD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('56', 'Guinean Franc', 'GNF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('57', 'Guatemalan Quetzal', 'GTQ');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('58', 'Guyanaese Dollar', 'GYD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('59', 'Hong Kong Dollar', 'HKD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('60', 'Honduran Lempira', 'HNL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('61', 'Croatian Kuna', 'HRK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('62', 'Haitian Gourde', 'HTG');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('63', 'Hungarian Forint', 'HUF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('64', 'Indonesian Rupiah', 'IDR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('65', 'Israeli New Sheqel', 'ILS');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('66', 'Manx pound', 'IMP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('67', 'Indian Rupee', 'INR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('68', 'Iraqi Dinar', 'IQD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('69', 'Iranian Rial', 'IRR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('70', 'Icelandic Króna', 'ISK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('71', 'Jersey Pound', 'JEP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('72', 'Jamaican Dollar', 'JMD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('73', 'Jordanian Dinar', 'JOD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('74', 'Japanese Yen', 'JPY');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('75', 'Kenyan Shilling', 'KES');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('76', 'Kyrgystani Som', 'KGS');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('77', 'Cambodian Riel', 'KHR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('78', 'Comorian Franc', 'KMF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('79', 'North Korean Won', 'KPW');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('80', 'South Korean Won', 'KRW');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('81', 'Kuwaiti Dinar', 'KWD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('82', 'Cayman Islands Dollar', 'KYD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('83', 'Kazakhstani Tenge', 'KZT');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('84', 'Laotian Kip', 'LAK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('85', 'Lebanese Pound', 'LBP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('86', 'Sri Lankan Rupee', 'LKR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('87', 'Liberian Dollar', 'LRD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('88', 'Lesotho Loti', 'LSL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('89', 'Lithuanian Litas', 'LTL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('90', 'Latvian Lats', 'LVL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('91', 'Libyan Dinar', 'LYD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('92', 'Moroccan Dirham', 'MAD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('93', 'Moldovan Leu', 'MDL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('94', 'Malagasy Ariary', 'MGA');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('95', 'Macedonian Denar', 'MKD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('96', 'Myanma Kyat', 'MMK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('97', 'Mongolian Tugrik', 'MNT');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('98', 'Macanese Pataca', 'MOP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('99', 'Mauritanian Ouguiya', 'MRO');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('100', 'Mauritian Rupee', 'MUR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('101', 'Maldivian Rufiyaa', 'MVR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('102', 'Malawian Kwacha', 'MWK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('103', 'Mexican Peso', 'MXN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('104', 'Malaysian Ringgit', 'MYR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('105', 'Mozambican Metical', 'MZN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('106', 'Namibian Dollar', 'NAD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('107', 'Nigerian Naira', 'NGN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('108', 'Nicaraguan Córdoba', 'NIO');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('109', 'Norwegian Krone', 'NOK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('110', 'Nepalese Rupee', 'NPR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('111', 'New Zealand Dollar', 'NZD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('112', 'Omani Rial', 'OMR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('113', 'Panamanian Balboa', 'PAB');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('114', 'Peruvian Nuevo Sol', 'PEN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('115', 'Papua New Guinean Kina', 'PGK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('116', 'Philippine Peso', 'PHP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('117', 'Pakistani Rupee', 'PKR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('118', 'Polish Zloty', 'PLN');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('119', 'Paraguayan Guarani', 'PYG');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('120', 'Qatari Rial', 'QAR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('121', 'Romanian Leu', 'RON');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('122', 'Serbian Dinar', 'RSD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('123', 'Russian Ruble', 'RUB');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('124', 'Rwandan Franc', 'RWF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('125', 'Saudi Riyal', 'SAR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('126', 'Solomon Islands Dollar', 'SBD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('127', 'Seychellois Rupee', 'SCR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('128', 'Sudanese Pound', 'SDG');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('129', 'Swedish Krona', 'SEK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('130', 'Singapore Dollar', 'SGD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('131', 'Saint Helena Pound', 'SHP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('132', 'Sierra Leonean Leone', 'SLL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('133', 'Somali Shilling', 'SOS');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('134', 'Surinamese Dollar', 'SRD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('135', 'São Tomé and Príncipe Dobra', 'STD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('136', 'Salvadoran Colón', 'SVC');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('137', 'Syrian Pound', 'SYP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('138', 'Swazi Lilangeni', 'SZL');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('139', 'Thai Baht', 'THB');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('140', 'Tajikistani Somoni', 'TJS');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('141', 'Turkmenistani Manat', 'TMT');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('142', 'Tunisian Dinar', 'TND');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('143', 'Tongan Paʻanga', 'TOP');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('144', 'Turkish Lira', 'TRY');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('145', 'Trinidad and Tobago Dollar', 'TTD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('146', 'New Taiwan Dollar', 'TWD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('147', 'Tanzanian Shilling', 'TZS');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('148', 'Ukrainian Hryvnia', 'UAH');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('149', 'Ugandan Shilling', 'UGX');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('150', 'United States Dollar', 'USD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('151', 'Uruguayan Peso', 'UYU');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('152', 'Uzbekistan Som', 'UZS');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('153', 'Venezuelan Bolívar Fuerte', 'VEF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('154', 'Vietnamese Dong', 'VND');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('155', 'Vanuatu Vatu', 'VUV');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('156', 'Samoan Tala', 'WST');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('157', 'CFA Franc BEAC', 'XAF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('158', 'Silver (troy ounce)', 'XAG');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('159', 'Gold (troy ounce)', 'XAU');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('160', 'East Caribbean Dollar', 'XCD');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('161', 'Special Drawing Rights', 'XDR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('162', 'CFA Franc BCEAO', 'XOF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('163', 'CFP Franc', 'XPF');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('164', 'Yemeni Rial', 'YER');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('165', 'South African Rand', 'ZAR');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('166', 'Zambian Kwacha (pre-2013)', 'ZMK');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('167', 'Zambian Kwacha', 'ZMW');")
    currency_data.append("INSERT INTO supported_currencies VALUES ('168', 'Zimbabwean Dollar', 'ZWL');")

    for sql in currency_data:
        db.engine.execute(sql)